version: '1'
services:
  myapp-main:
    image: movieapi:latest
    ports:
      - 8080:8080
    environment:
#      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/final_sdat_qap_2023
      - spring.datasource.url=jdbc:mysql://database-1.ceu5peoa6v6x.us-east-1.rds.amazonaws.com/final_sprint
      - spring.datasource.password=password
      - spring.datasource.username=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

