insert into movie (title, genre, review) values ('Armour of God II: Operation Condor (Operation Condor) (Fei ying gai wak)', 'Action|Adventure|Comedy', 3);
insert into movie (title, genre, review) values ('Skin Game, The', 'Drama', 2);
insert into movie (title, genre, review) values ('Brothers: The Return', 'Crime|Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Sabretooth', 'Action|Adventure|Horror|Sci-Fi|Thriller', 1);
insert into movie (title, genre, review) values ('Simple Men', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Signs', 'Romance', 5);
insert into movie (title, genre, review) values ('Cry of the Owl, The', 'Drama|Thriller', 4);
insert into movie (title, genre, review) values ('Mumford', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Red Eye', 'Horror|Thriller', 4);
insert into movie (title, genre, review) values ('Nude Bomb, The', 'Comedy', 2);
insert into movie (title, genre, review) values ('Horse Feathers', 'Comedy', 3);
insert into movie (title, genre, review) values ('Austenland', 'Comedy|Romance', 3);
insert into movie (title, genre, review) values ('Night and Day', 'Drama|Musical', 3);
insert into movie (title, genre, review) values ('Je, tu, il, elle (I, You, He, She)', 'Drama', 3);
insert into movie (title, genre, review) values ('Love Trap, The', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values ('Friends of Eddie Coyle, The', 'Crime|Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Where Are the Dreams of Youth? (Seishun no yume imaizuko)', 'Drama', 1);
insert into movie (title, genre, review) values ('Marathon Family, The (Maratonci Trce Pocasni Krug)', 'Comedy', 1);
insert into movie (title, genre, review) values ('I Hired a Contract Killer', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Not Another Not Another Movie', 'Comedy', 4);
insert into movie (title, genre, review) values ('Defiance', 'Action|Crime|Drama', 4);
insert into movie (title, genre, review) values ('Cheech & Chong''s The Corsican Brothers', 'Comedy', 1);
insert into movie (title, genre, review) values ('Cocaine Cowboys II: Hustlin'' With the Godmother', 'Crime|Documentary', 4);
insert into movie (title, genre, review) values ('Human Desire', 'Drama|Film-Noir', 1);
insert into movie (title, genre, review) values ('Nekromantik', 'Comedy|Horror', 4);
insert into movie (title, genre, review) values ('Grave Secrets (Silent Screams)', 'Horror', 2);
insert into movie (title, genre, review) values ('Ricky Rapper (Risto Räppääjä)', 'Comedy|Musical', 5);
insert into movie (title, genre, review) values ('Joe Dirt', 'Adventure|Comedy|Mystery|Romance', 3);
insert into movie (title, genre, review) values ('Casper', 'Adventure|Children', 1);
insert into movie (title, genre, review) values ('Road to Redemption', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('Windmill Movie, The', 'Documentary', 1);
insert into movie (title, genre, review) values ('Caliber 9', 'Action|Crime|Thriller', 3);
insert into movie (title, genre, review) values ('Tale of the Mummy', 'Adventure|Fantasy|Horror', 2);
insert into movie (title, genre, review) values ('In China They Eat Dogs (I Kina spiser de hunde)', 'Action|Comedy', 4);
insert into movie (title, genre, review) values ('Mortal Thoughts', 'Mystery|Thriller', 5);
insert into movie (title, genre, review) values ('Badman''s Territory', 'Action|Drama|Western', 2);
insert into movie (title, genre, review) values ('Lost Battalion, The', 'Action|Drama|War', 2);
insert into movie (title, genre, review) values ('Sherlock Holmes: The Woman in Green', 'Mystery', 5);
insert into movie (title, genre, review) values ('We''re Not Dressing', 'Comedy|Musical', 5);
insert into movie (title, genre, review) values ('Nanny McPhee', 'Children|Comedy|Fantasy', 5);
insert into movie (title, genre, review) values ('Eden', 'Drama', 5);
insert into movie (title, genre, review) values ('Killing of Sister George, The', 'Drama', 3);
insert into movie (title, genre, review) values ('Miss Granny', 'Comedy|Fantasy', 2);
insert into movie (title, genre, review) values ('Help!', 'Comedy|Musical', 5);
insert into movie (title, genre, review) values ('Sharktopus', 'Action|Horror|Sci-Fi', 1);
insert into movie (title, genre, review) values ('Un vampiro para dos', 'Comedy|Horror', 5);
insert into movie (title, genre, review) values ('Where the Red Fern Grows', 'Drama', 2);
insert into movie (title, genre, review) values ('Ménage (Tenue de soirée)', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Alvin and the Chipmunks: The Squeakquel', 'Animation|Children|Comedy|Musical', 5);
insert into movie (title, genre, review) values ('Save the Last Dance 2', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Dr. Mabuse: The Gambler (Dr. Mabuse, der Spieler)', 'Crime|Mystery|Thriller', 5);
insert into movie (title, genre, review) values ('Four Lions', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('My Friend Henry (Ystäväni Henry)', 'Children|Drama', 5);
insert into movie (title, genre, review) values ('In the Hands of the Gods', 'Documentary', 3);
insert into movie (title, genre, review) values ('Life with Father', 'Comedy', 1);
insert into movie (title, genre, review) values ('London', 'Drama', 3);
insert into movie (title, genre, review) values ('Waiting for Superman', 'Documentary', 1);
insert into movie (title, genre, review) values ('Michael the Brave (Mihai Viteazul)', 'Action|Drama', 5);
insert into movie (title, genre, review) values ('Moment of Truth, The (Il momento della verità)', 'Drama', 3);
insert into movie (title, genre, review) values ('After Five in the Jungle (Nach Fünf im Urwald)', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('...tick... tick... tick...', 'Action|Drama', 1);
insert into movie (title, genre, review) values ('My Little Eye', 'Horror|Mystery|Thriller', 1);
insert into movie (title, genre, review) values ('The Princess of Egypt', 'Drama', 1);
insert into movie (title, genre, review) values ('Samaritan Girl (Samaria)', 'Drama', 5);
insert into movie (title, genre, review) values ('Chasers, The (Jakten)', 'Drama|Romance|Thriller', 4);
insert into movie (title, genre, review) values ('Chain of Fools', 'Comedy|Crime', 2);
insert into movie (title, genre, review) values ('God''s Comedy (A Comédia de Deus)', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Symmetry (Symetria)', 'Crime|Drama', 3);
insert into movie (title, genre, review) values ('Elmer Gantry', 'Drama', 4);
insert into movie (title, genre, review) values ('Pagemaster, The', 'Action|Adventure|Animation|Children|Fantasy', 2);
insert into movie (title, genre, review) values ('Falcon and the Snowman, The', 'Drama|Thriller', 1);
insert into movie (title, genre, review) values ('Saawariya', 'Drama|Musical|Romance', 3);
insert into movie (title, genre, review) values ('Burden of Dreams', 'Documentary', 1);
insert into movie (title, genre, review) values ('Maniacts', 'Action|Comedy|Drama|Horror|Romance', 1);
insert into movie (title, genre, review) values ('It Rains in My Village (Bice skoro propast sveta)', 'Drama', 3);
insert into movie (title, genre, review) values ('St. Elmo''s Fire', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Empire of Dreams: The Story of the ''Star Wars'' Trilogy', 'Documentary', 1);
insert into movie (title, genre, review) values ('Eye for an Eye, An (Silmä silmästä)', 'Horror', 2);
insert into movie (title, genre, review) values ('Sin of Harold Diddlebock, The', 'Comedy', 4);
insert into movie (title, genre, review) values ('Brother of Sleep (Schlafes Bruder)', 'Drama', 2);
insert into movie (title, genre, review) values ('A Summer in St. Tropez', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Cold Mountain', 'Drama|Romance|War', 4);
insert into movie (title, genre, review) values ('Benigni', 'Animation|Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Great Ecstasy of Woodcarver Steiner, The (Große Ekstase des Bildschnitzers Steiner, Die)', 'Documentary', 4);
insert into movie (title, genre, review) values ('Time of Peace (Tempos de Paz)', 'Drama', 1);
insert into movie (title, genre, review) values ('Come to the Stable', 'Drama', 3);
insert into movie (title, genre, review) values ('Stay Cool', 'Comedy|Drama|Romance', 1);
insert into movie (title, genre, review) values ('Smiles of a Summer Night (Sommarnattens leende)', 'Comedy|Romance', 3);
insert into movie (title, genre, review) values ('Out Late ', 'Documentary', 1);
insert into movie (title, genre, review) values ('Greystoke: The Legend of Tarzan, Lord of the Apes', 'Adventure|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Mean Season, The', 'Crime|Thriller', 4);
insert into movie (title, genre, review) values ('Crazy Kind of Love', 'Comedy|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Generation War', 'Drama|War', 2);
insert into movie (title, genre, review) values ('Paleface, The', 'Comedy', 4);
insert into movie (title, genre, review) values ('Taste of Tea, The (Cha no aji)', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Lolita', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Human Family Tree, The', 'Documentary', 1);
insert into movie (title, genre, review) values ('Bag It', 'Documentary', 3);
insert into movie (title, genre, review) values ('Giant Mechanical Man, The', 'Comedy|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Tell It to the Marines', 'Comedy|Drama|Romance|War', 2);
insert into movie (title, genre, review) values ('Everyone Else (Alle Anderen)', 'Drama|Romance', 5);
insert into movie (title, genre, review) values ('Air Bud', 'Children|Comedy', 3);
insert into movie (title, genre, review) values ('Yellow', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('In Search of the Castaways', 'Adventure|Children', 4);
insert into movie (title, genre, review) values ('Better This World', 'Documentary', 2);
insert into movie (title, genre, review) values ('Lady Jane', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Penn & Teller Get Killed', 'Adventure|Comedy', 4);
insert into movie (title, genre, review) values ('Footprints of a Spirit, The (Huellas de un espíritu)', 'Documentary', 2);
insert into movie (title, genre, review) values ('Life in Flight ', 'Drama', 2);
insert into movie (title, genre, review) values ('Rent-a-Cat', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Beyond the Stars', 'Drama|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Will Success Spoil Rock Hunter?', 'Comedy|Romance', 3);
insert into movie (title, genre, review) values ('Year My Parents Went on Vacation, The (O Ano em Que Meus Pais Saíram de Férias)', 'Drama', 3);
insert into movie (title, genre, review) values ('Georg', 'Drama|Musical', 4);
insert into movie (title, genre, review) values ('Thomas Pynchon: A Journey into the Mind of P.', 'Documentary', 5);
insert into movie (title, genre, review) values ('Withnail & I', 'Comedy', 4);
insert into movie (title, genre, review) values ('Place at the Table, A', 'Documentary', 3);
insert into movie (title, genre, review) values ('Hollywood Shuffle', 'Comedy', 2);
insert into movie (title, genre, review) values ('Subway', 'Crime|Drama|Romance|Thriller', 3);
insert into movie (title, genre, review) values ('Dark Angel (I Come in Peace)', 'Action|Horror|Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values ('Sabata', 'Action|Western', 3);
insert into movie (title, genre, review) values ('High Tech, Low Life', 'Documentary', 1);
insert into movie (title, genre, review) values ('World Trade Center', 'Drama', 2);
insert into movie (title, genre, review) values ('That Thing You Do!', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Marie and Bruce', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Man with the Movie Camera, The (Chelovek s kino-apparatom)', 'Documentary', 4);
insert into movie (title, genre, review) values ('Dove, The', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Rumble in the Bronx (Hont faan kui)', 'Action|Adventure|Comedy|Crime', 3);
insert into movie (title, genre, review) values ('Genesis', 'Drama|Horror', 2);
insert into movie (title, genre, review) values ('Too Shy to Try (Je suis timide... mais je me soigne)', 'Comedy', 3);
insert into movie (title, genre, review) values ('My Name Is Bruce', 'Comedy|Horror', 3);
insert into movie (title, genre, review) values ('There''s No Business Like Show Business', 'Musical', 2);
insert into movie (title, genre, review) values ('Stage Fright', 'Mystery|Romance|Thriller', 3);
insert into movie (title, genre, review) values ('Days Between, The (In den Tag hinein)', 'Drama', 5);
insert into movie (title, genre, review) values ('Terminator 3: Rise of the Machines', 'Action|Adventure|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Hellhounds on My Trail', 'Documentary', 3);
insert into movie (title, genre, review) values ('Lethal Weapon 2', 'Action|Comedy|Crime|Drama', 4);
insert into movie (title, genre, review) values ('I Am the Law', 'Crime|Drama', 1);
insert into movie (title, genre, review) values ('Puppet Master: Axis of Evil (Puppet Master 10)', 'Horror', 2);
insert into movie (title, genre, review) values ('Mike Tyson:  Undisputed Truth', 'Comedy', 4);
insert into movie (title, genre, review) values ('Santa Claus Is a Stinker (Le Père Noël est une ordure)', 'Comedy', 4);
insert into movie (title, genre, review) values ('Mother of Mine (Äideistä parhain)', 'Drama', 3);
insert into movie (title, genre, review) values ('House of Sand (Casa de Areia)', 'Drama', 3);
insert into movie (title, genre, review) values ('Hard Word, The', 'Comedy|Crime|Drama|Thriller', 4);
insert into movie (title, genre, review) values ('Bitch Hug (Bitchkram)', 'Drama', 4);
insert into movie (title, genre, review) values ('Midnight Run', 'Action|Comedy|Crime|Thriller', 1);
insert into movie (title, genre, review) values ('Duel in the Sun', 'Western', 5);
insert into movie (title, genre, review) values ('Cinderella', 'Animation|Children|Fantasy|Romance', 1);
insert into movie (title, genre, review) values ('Band''s Visit, The (Bikur Ha-Tizmoret)', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Martha Marcy May Marlene', 'Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Amber Lake ', 'Drama|Thriller', 4);
insert into movie (title, genre, review) values ('Teen Spirit', 'Comedy', 2);
insert into movie (title, genre, review) values ('Big Picture, The (L''homme qui voulait vivre sa vie)', 'Drama', 1);
insert into movie (title, genre, review) values ('Dracula (Bram Stoker''s Dracula)', 'Fantasy|Horror|Romance|Thriller', 1);
insert into movie (title, genre, review) values ('Native Son', 'Drama', 5);
insert into movie (title, genre, review) values ('Twelve', 'Crime|Drama|Thriller', 4);
insert into movie (title, genre, review) values ('All the Right Moves', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Dish, The', 'Comedy', 5);
insert into movie (title, genre, review) values ('Wild Hearts Can''t Be Broken', 'Drama|Romance', 5);
insert into movie (title, genre, review) values ('Irreconcilable Differences', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values ('Lodger, The', 'Crime|Drama|Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('Independence Day (a.k.a. ID4)', 'Action|Adventure|Sci-Fi|Thriller', 2);
insert into movie (title, genre, review) values ('Master, The', 'Drama', 2);
insert into movie (title, genre, review) values ('Twilight Saga: Eclipse, The', 'Fantasy|Romance|Thriller|IMAX', 4);
insert into movie (title, genre, review) values ('Analyze This', 'Comedy', 5);
insert into movie (title, genre, review) values ('Body/Cialo', 'Comedy|Drama|Mystery', 2);
insert into movie (title, genre, review) values ('Bonhoeffer: Agent of Grace', 'Drama', 3);
insert into movie (title, genre, review) values ('Dilettante, La', 'Comedy', 3);
insert into movie (title, genre, review) values ('Long John Silver', 'Action|Adventure', 3);
insert into movie (title, genre, review) values ('Other Side of Heaven, The', 'Adventure|Drama', 5);
insert into movie (title, genre, review) values ('Vincere', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('The Five Man Army', 'Western', 5);
insert into movie (title, genre, review) values ('Cop Land', 'Action|Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Rose Seller, The (La vendedora de rosas)', 'Drama', 1);
insert into movie (title, genre, review) values ('Soap and Water', 'Comedy', 3);
insert into movie (title, genre, review) values ('Ladies They Talk About', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Scanners', 'Horror|Sci-Fi|Thriller', 2);
insert into movie (title, genre, review) values ('Lagaan: Once Upon a Time in India', 'Comedy|Drama|Musical|Romance', 2);
insert into movie (title, genre, review) values ('Johnny Cash at Folsom Prison', 'Documentary', 2);
insert into movie (title, genre, review) values ('Norman', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Dracula', 'Horror', 1);
insert into movie (title, genre, review) values ('Man in the Saddle', 'Western', 3);
insert into movie (title, genre, review) values ('Il cappotto di legno', '(no genres listed)', 4);
insert into movie (title, genre, review) values ('Falls, The', 'Drama|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Stealing Beauty', 'Drama', 4);
insert into movie (title, genre, review) values ('Cold Storage', 'Thriller', 2);
insert into movie (title, genre, review) values ('Pallbearer, The', 'Comedy', 4);
insert into movie (title, genre, review) values ('Family Plot', 'Comedy|Thriller', 3);
insert into movie (title, genre, review) values ('Beyond the Mind''s Eye', 'Animation|Comedy', 4);
insert into movie (title, genre, review) values ('Interview with the Vampire: The Vampire Chronicles', 'Drama|Horror', 1);
insert into movie (title, genre, review) values ('Amar Akbar Anthony', 'Action|Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Quality Street', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Belly of an Architect, The', 'Drama', 4);
insert into movie (title, genre, review) values ('For a Woman (Pour une femme)', 'Drama|Romance|War', 3);
insert into movie (title, genre, review) values ('Growing Pains', 'Comedy', 3);
insert into movie (title, genre, review) values ('Two of Us, The (Le vieil homme et l''enfant)', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Date Movie', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('Pontiac Moon', 'Drama', 4);
insert into movie (title, genre, review) values ('Littlerock', 'Drama', 3);
insert into movie (title, genre, review) values ('Nirvana', 'Action|Sci-Fi', 2);
insert into movie (title, genre, review) values ('Alphabet Killer, The', 'Crime', 2);
insert into movie (title, genre, review) values ('Swing Shift', 'Drama', 3);
insert into movie (title, genre, review) values ('Crumb', 'Documentary', 1);
insert into movie (title, genre, review) values ('Wedding Singer, The', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('Stanley and Livingstone', 'Adventure|Drama', 3);
insert into movie (title, genre, review) values ('For Roseanna (Roseanna''s Grave)', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values ('Fist of Jesus', '(no genres listed)', 1);
insert into movie (title, genre, review) values ('Speedway Junky', 'Drama', 3);
insert into movie (title, genre, review) values ('Dirty Bomb', 'Comedy', 1);
insert into movie (title, genre, review) values ('Highlander II: The Quickening', 'Action|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Thirteen Women', 'Drama|Mystery', 5);
insert into movie (title, genre, review) values ('Breakfast at Tiffany''s', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Walking Dead, The', 'Drama|War', 1);
insert into movie (title, genre, review) values ('Man Who Copied, The (Homem Que Copiava, O)', 'Comedy|Crime|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Dollman vs. Demonic Toys', 'Action|Fantasy|Horror', 4);
insert into movie (title, genre, review) values ('Home Page', 'Documentary', 5);
insert into movie (title, genre, review) values ('Bad Lieutenant: Port of Call New Orleans', 'Crime|Drama', 3);
insert into movie (title, genre, review) values ('Page Eight', 'Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Yearling, The', 'Children|Drama', 1);
insert into movie (title, genre, review) values ('Scott Walker: 30 Century Man', 'Documentary|Musical', 3);
insert into movie (title, genre, review) values ('Plenty', 'Drama', 1);
insert into movie (title, genre, review) values ('Universal Soldier: The Return', 'Action|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Toy Story 3', 'Adventure|Animation|Children|Comedy|Fantasy|IMAX', 3);
insert into movie (title, genre, review) values ('James Dean Remembered', 'Documentary', 1);
insert into movie (title, genre, review) values ('Wild Things', 'Crime|Drama|Mystery|Thriller', 5);
insert into movie (title, genre, review) values ('War of the Buttons', 'Adventure|Children|Drama', 5);
insert into movie (title, genre, review) values ('Blood in the Mobile', 'Documentary', 5);
insert into movie (title, genre, review) values ('Those Daring Young Men in Their Jaunty Jalopies', 'Adventure|Comedy|Crime|Romance', 5);
insert into movie (title, genre, review) values ('Project A (''A'' gai waak)', 'Action|Comedy', 2);
insert into movie (title, genre, review) values ('Adventureland', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Shit Year', 'Drama', 4);
insert into movie (title, genre, review) values ('Mamitas', 'Drama', 5);
insert into movie (title, genre, review) values ('Life During Wartime', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Twist', 'Drama', 2);
insert into movie (title, genre, review) values ('Clear History', 'Comedy', 4);
insert into movie (title, genre, review) values ('Sasori', 'Action', 5);
insert into movie (title, genre, review) values ('Consenting Adults', 'Thriller', 3);
insert into movie (title, genre, review) values ('Om Jai Jagadish', 'Drama', 2);
insert into movie (title, genre, review) values ('Oscar and Lucinda (a.k.a. Oscar & Lucinda)', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Ricky & Barabba', 'Comedy', 1);
insert into movie (title, genre, review) values ('As Tears Go By (Wong gok ka moon)', 'Crime|Drama', 1);
insert into movie (title, genre, review) values ('Predator', 'Action|Sci-Fi|Thriller', 1);
insert into movie (title, genre, review) values ('Voices of Iraq', 'Documentary', 2);
insert into movie (title, genre, review) values ('SOS - en segelsällskapsresa', 'Comedy', 2);
insert into movie (title, genre, review) values ('Heart of a Lion', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values ('Adventures of Mark Twain, The', 'Adventure|Drama', 3);
insert into movie (title, genre, review) values ('Designing Woman', 'Comedy', 1);
insert into movie (title, genre, review) values ('Coyote Ugly', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Diary of a Wimpy Kid: Rodrick Rules', 'Comedy', 4);
insert into movie (title, genre, review) values ('No Way Back', 'Action|Crime|Drama|Thriller', 4);
insert into movie (title, genre, review) values ('Aspen', 'Documentary', 4);
insert into movie (title, genre, review) values ('House of Tolerance', 'Drama', 3);
insert into movie (title, genre, review) values ('Mysterious Skin', 'Drama|Mystery', 4);
insert into movie (title, genre, review) values ('Armageddon 2012', 'Sci-Fi', 4);
insert into movie (title, genre, review) values ('Mr. Accident', 'Comedy', 5);
insert into movie (title, genre, review) values ('Duellists, The', 'Action|War', 5);
insert into movie (title, genre, review) values ('Singham', 'Action|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Ghoulies', 'Horror', 5);
insert into movie (title, genre, review) values ('Bathory', 'Drama|Fantasy', 1);
insert into movie (title, genre, review) values ('Ernest Goes to Camp', 'Comedy', 3);
insert into movie (title, genre, review) values ('Lock, Stock & Two Smoking Barrels', 'Comedy|Crime|Thriller', 5);
insert into movie (title, genre, review) values ('High Time (Big Daddy)', 'Comedy|Musical', 3);
insert into movie (title, genre, review) values ('Fox and the Hound, The', 'Animation|Children|Drama', 3);
insert into movie (title, genre, review) values ('Up in the Air', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Budrus', 'Documentary', 1);
insert into movie (title, genre, review) values ('Young Master, The (Shi di chu ma)', 'Action|Comedy', 2);
insert into movie (title, genre, review) values ('Last Time I Saw Paris, The', 'Drama', 4);
insert into movie (title, genre, review) values ('Harvard Man', 'Crime|Drama|Romance|Thriller', 3);
insert into movie (title, genre, review) values ('Man with the Screaming Brain', 'Adventure|Comedy|Sci-Fi', 2);
insert into movie (title, genre, review) values ('Powers of Ten', 'Documentary', 4);
insert into movie (title, genre, review) values ('Light Gradient', 'Drama|Mystery|Romance', 4);
insert into movie (title, genre, review) values ('Pauline détective', 'Comedy', 3);
insert into movie (title, genre, review) values ('Cat Ballou', 'Comedy|Western', 3);
insert into movie (title, genre, review) values ('Kairat', 'Drama', 4);
insert into movie (title, genre, review) values ('Detroit Rock City', 'Comedy', 1);
insert into movie (title, genre, review) values ('Satan''s Little Helper', 'Comedy|Horror', 1);
insert into movie (title, genre, review) values ('About Schmidt', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Charlie Bartlett', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('To Sleep with Anger', 'Drama', 2);
insert into movie (title, genre, review) values ('Will', 'Children|Drama', 3);
insert into movie (title, genre, review) values ('First Strike (Police Story 4: First Strike) (Ging chaat goo si 4: Ji gaan daan yam mo)', 'Action|Adventure|Comedy|Thriller', 1);
insert into movie (title, genre, review) values ('Remember the Daze (Beautiful Ordinary, The)', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('Mademoiselle Chambon', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Held Up', 'Comedy', 2);
insert into movie (title, genre, review) values ('Beethoven''s 5th', 'Adventure|Children|Comedy', 1);
insert into movie (title, genre, review) values ('Beyond the Gates of Splendor', 'Documentary', 4);
insert into movie (title, genre, review) values ('How to Succeed in Business Without Really Trying', 'Comedy|Musical', 2);
insert into movie (title, genre, review) values ('Replicant', 'Action|Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values ('Woman of Antwerp', 'Drama', 3);
insert into movie (title, genre, review) values ('Against The Sun', 'Adventure', 3);
insert into movie (title, genre, review) values ('Best and the Brightest, The', 'Comedy', 3);
insert into movie (title, genre, review) values ('Final Option, The (Who Dares Wins)', 'Action|War', 4);
insert into movie (title, genre, review) values ('Princess Ka''iulani', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Bank, The', 'Comedy', 2);
insert into movie (title, genre, review) values ('Boys', 'Drama', 3);
insert into movie (title, genre, review) values ('Ordinary Decent Criminal', 'Comedy|Crime', 4);
insert into movie (title, genre, review) values ('Sundown', 'Drama|War', 3);
insert into movie (title, genre, review) values ('Tall Target, The', 'Adventure|Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Against the Ropes', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Age of Stupid, The', 'Documentary', 3);
insert into movie (title, genre, review) values ('Once Were Warriors', 'Crime|Drama', 4);
insert into movie (title, genre, review) values ('Gentle Breeze in the Village, A (Tennen kokekkô) ', 'Drama', 3);
insert into movie (title, genre, review) values ('Babylon 5', 'Sci-Fi', 3);
insert into movie (title, genre, review) values ('Flesh for Frankenstein (a.k.a. Andy Warhol''s Frankenstein)', 'Drama|Horror|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Nightmare on Elm Street 3: Dream Warriors, A', 'Horror|Thriller', 2);
insert into movie (title, genre, review) values ('Tough Guys', 'Comedy', 5);
insert into movie (title, genre, review) values ('Great!', 'Comedy', 5);
insert into movie (title, genre, review) values ('Brother Bear 2', 'Adventure|Animation|Children|Comedy|Fantasy', 4);
insert into movie (title, genre, review) values ('Day of the Dolphin, The', 'Drama', 5);
insert into movie (title, genre, review) values ('Human Trafficking', 'Crime|Drama|Mystery|Thriller', 2);
insert into movie (title, genre, review) values ('Assassination of a High School President', 'Comedy|Drama|Mystery', 3);
insert into movie (title, genre, review) values ('Barfi!', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Signs', 'Romance', 1);
insert into movie (title, genre, review) values ('Santa Fe Trail', 'Drama|Romance|Western', 4);
insert into movie (title, genre, review) values ('Deadgirl', 'Horror', 3);
insert into movie (title, genre, review) values ('Big Town, The', 'Drama|Romance|Thriller', 5);
insert into movie (title, genre, review) values ('13 Ghosts', 'Horror', 2);
insert into movie (title, genre, review) values ('Carrie', 'Drama|Horror', 5);
insert into movie (title, genre, review) values ('Transcendence', 'Drama|Sci-Fi|IMAX', 4);
insert into movie (title, genre, review) values ('Never Give a Sucker an Even Break', 'Comedy|Musical', 3);
insert into movie (title, genre, review) values ('Jesus of Nazareth', 'Drama', 4);
insert into movie (title, genre, review) values ('Toy, The (Le jouet)', 'Comedy', 5);
insert into movie (title, genre, review) values ('Kidnapped', 'Adventure|Children|Drama', 2);
insert into movie (title, genre, review) values ('Mischief', 'Comedy|Romance', 3);
insert into movie (title, genre, review) values ('Before I Go to Sleep', 'Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('Patton Oswalt: Tragedy Plus Comedy Equals Time', 'Comedy', 1);
insert into movie (title, genre, review) values ('Cutting Edge: Going for the Gold, The', 'Comedy|Drama|Romance', 3);
insert into movie (title, genre, review) values ('Jackass 2.5', 'Comedy|Documentary', 1);
insert into movie (title, genre, review) values ('Hypnotist, The (Hypnotisören)', 'Thriller', 5);
insert into movie (title, genre, review) values ('Rollerball', 'Action|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Jerry Seinfeld: ''I''m Telling You for the Last Time''', 'Comedy|Documentary', 5);
insert into movie (title, genre, review) values ('More Than a Game', 'Documentary', 4);
insert into movie (title, genre, review) values ('Ghosts of Girlfriends Past', 'Comedy|Fantasy|Romance', 2);
insert into movie (title, genre, review) values ('Postcards From the Edge', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('Tesla: Master of Lightning', 'Documentary', 2);
insert into movie (title, genre, review) values ('The Mark of Cain', 'Documentary|Drama', 1);
insert into movie (title, genre, review) values ('Jean-Luc Cinema Godard', 'Documentary', 1);
insert into movie (title, genre, review) values ('Danger: Diabolik (Diabolik)', 'Action|Crime|Thriller', 5);
insert into movie (title, genre, review) values ('Psycho', 'Crime|Horror|Thriller', 2);
insert into movie (title, genre, review) values ('Corruptor, The', 'Action|Crime|Drama|Thriller', 3);
insert into movie (title, genre, review) values ('The Boy Next Door', 'Thriller', 5);
insert into movie (title, genre, review) values ('Perfect Circle, The (Savrseni krug)', 'Drama|War', 5);
insert into movie (title, genre, review) values ('Galapagos Affair: Satan Came to Eden, The', 'Crime|Documentary|Mystery', 5);
insert into movie (title, genre, review) values ('Rio Sex Comedy', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Nuts', 'Drama', 1);
insert into movie (title, genre, review) values ('Shepherd: Border Patrol, The', 'Action|Crime|Thriller', 3);
insert into movie (title, genre, review) values ('Cool It', 'Documentary', 5);
insert into movie (title, genre, review) values ('Hamlet', 'Crime|Drama|Romance|Thriller', 4);
insert into movie (title, genre, review) values ('Good Advice', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values ('Amish Murder, An', 'Action|Crime|Drama', 1);
insert into movie (title, genre, review) values ('Cheerleaders, The', 'Comedy', 4);
insert into movie (title, genre, review) values ('Riders', 'Action|Crime|Thriller', 5);
insert into movie (title, genre, review) values ('North and South, Book I', 'Drama|Romance|War', 3);
insert into movie (title, genre, review) values ('Zero Effect', 'Comedy|Mystery|Thriller', 5);
insert into movie (title, genre, review) values ('Private Benjamin', 'Comedy', 1);
insert into movie (title, genre, review) values ('Expired', 'Comedy|Drama|Romance', 3);
insert into movie (title, genre, review) values ('Mina Tannenbaum', 'Drama', 1);
insert into movie (title, genre, review) values ('Onibaba', 'Drama|Horror|War', 3);
insert into movie (title, genre, review) values ('Adventure in Baltimore', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('Anatomy (Anatomie)', 'Horror', 4);
insert into movie (title, genre, review) values ('Heli', 'Crime|Drama', 4);
insert into movie (title, genre, review) values ('Blue and the Gray, The', 'Drama|War', 3);
insert into movie (title, genre, review) values ('Hostel', 'Horror', 5);
insert into movie (title, genre, review) values ('Smurfs, The', 'Animation|Children|Comedy', 1);
insert into movie (title, genre, review) values ('Billy Liar', 'Comedy', 5);
insert into movie (title, genre, review) values ('Glenn Miller Story, The', 'Drama', 5);
insert into movie (title, genre, review) values ('Lego: The Adventures of Clutch Powers', 'Action|Animation', 4);
insert into movie (title, genre, review) values ('Last Hard Men, The', 'Western', 3);
insert into movie (title, genre, review) values ('Soloalbum', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Nightmare on Elm Street, A', 'Horror|Thriller', 2);
insert into movie (title, genre, review) values ('Hanging Tree, The', 'Drama|Romance|Western', 3);
insert into movie (title, genre, review) values ('Into the Sun', 'Action|Adventure|Thriller', 1);
insert into movie (title, genre, review) values ('Rånarna', 'Action|Crime|Thriller', 5);
insert into movie (title, genre, review) values ('Ali G Indahouse', 'Comedy', 4);
insert into movie (title, genre, review) values ('Varasto', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Beeswax', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Slacker 2011', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Death at a Funeral', 'Comedy', 4);
insert into movie (title, genre, review) values ('World, The (Shijie)', 'Drama', 4);
insert into movie (title, genre, review) values ('The Invitation', 'Drama|Horror|Thriller', 1);
insert into movie (title, genre, review) values ('Mind Game', 'Adventure|Animation|Comedy|Fantasy|Romance|Sci-Fi', 4);
insert into movie (title, genre, review) values ('Come Undone (Presque Rien)', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Right Kind of Wrong, The', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Long Day''s Journey Into Night', 'Drama', 5);
insert into movie (title, genre, review) values ('Riding Alone for Thousands of Miles (Qian li zou dan qi)', 'Drama', 2);
insert into movie (title, genre, review) values ('Pillow Book, The', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Day The Earth Froze, The (Sampo)', 'Adventure|Fantasy', 2);
insert into movie (title, genre, review) values ('Ziggy Stardust and the Spiders from Mars', 'Documentary|Musical', 5);
insert into movie (title, genre, review) values ('Band of the Hand', 'Action|Crime|Drama', 1);
insert into movie (title, genre, review) values ('Trouble with Harry, The', 'Comedy|Mystery', 1);
insert into movie (title, genre, review) values ('Heaven Can Wait', 'Comedy', 5);
insert into movie (title, genre, review) values ('Vacation from Marriage', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Castle of the Living Dead (Castello Dei Morti Vivi, Il)', 'Horror|Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values ('Internes Can''t Take Money', 'Crime|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Crossing Delancey', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('Testament of Orpheus, The (Testament d''Orphée)', 'Drama', 4);
insert into movie (title, genre, review) values ('Late Bloomers', 'Comedy', 1);
insert into movie (title, genre, review) values ('Diabolique', 'Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Step Up All In', 'Drama|Musical|Romance', 5);
insert into movie (title, genre, review) values ('Pier, The (Jetée, La)', 'Romance|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Kings of the Sun', 'Adventure|Drama|Thriller', 4);
insert into movie (title, genre, review) values ('Light Gradient', 'Drama|Mystery|Romance', 4);
insert into movie (title, genre, review) values ('Lock Up', 'Action|Adventure|Crime|Drama|Thriller', 4);
insert into movie (title, genre, review) values ('Densha otoko (Train Man)', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Blast from the Past', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values ('Lot Like Love, A', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values ('Happy New Year (La Bonne Année)', 'Comedy|Crime|Drama', 2);
insert into movie (title, genre, review) values ('Conjuring, The', 'Horror|Thriller', 2);
insert into movie (title, genre, review) values ('Great Beauty, The (Grande Bellezza, La)', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Afstiros katallilo', 'Comedy', 1);
insert into movie (title, genre, review) values ('Post Mortem', 'Drama', 3);
insert into movie (title, genre, review) values ('Ready to Rumble', 'Comedy', 3);
insert into movie (title, genre, review) values ('Country Strong', 'Drama|Musical|Romance', 2);
insert into movie (title, genre, review) values ('Inside Job', 'Documentary', 4);
insert into movie (title, genre, review) values ('Minus Man, The', 'Drama|Mystery', 2);
insert into movie (title, genre, review) values ('Age of Innocence, The', 'Drama', 4);
insert into movie (title, genre, review) values ('Black Lightning (Chernaya Molniya)', 'Action|Adventure|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Hour of the Gun', 'Western', 3);
insert into movie (title, genre, review) values ('Winnie the Pooh and Tigger Too', 'Animation|Children', 3);
insert into movie (title, genre, review) values ('Olsen Gang on the Track, The (Olsen-banden på sporet)', 'Comedy|Crime', 4);
insert into movie (title, genre, review) values ('Love, Money, Love', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Young Lions, The', 'Drama|War', 5);
insert into movie (title, genre, review) values ('Informer, The', 'Crime|Drama', 4);
insert into movie (title, genre, review) values ('Hallam Foe (Mister Foe)', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Devil''s Playground', 'Documentary', 4);
insert into movie (title, genre, review) values ('Ong-Bak 3: The Final Battle (Ong Bak 3)', 'Action', 2);
insert into movie (title, genre, review) values ('Road House', 'Drama|Film-Noir', 2);
insert into movie (title, genre, review) values ('Love in the Afternoon', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Love Jones', 'Romance', 2);
insert into movie (title, genre, review) values ('Good Luck Chuck', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Eight Crazy Nights (Adam Sandler''s Eight Crazy Nights)', 'Animation|Comedy|Musical', 5);
insert into movie (title, genre, review) values ('Stormy Monday', 'Crime|Drama', 1);
insert into movie (title, genre, review) values ('La Belle Verte', 'Comedy', 2);
insert into movie (title, genre, review) values ('Cheap Thrills', 'Comedy|Thriller', 2);
insert into movie (title, genre, review) values ('Frankenweenie', 'Animation|Comedy|Horror|IMAX', 1);
insert into movie (title, genre, review) values ('Born Romantic', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Out of Balance: ExxonMobil''s Impact on Climate Change', 'Documentary', 5);
insert into movie (title, genre, review) values ('Ticking Clock', 'Action|Crime|Mystery|Sci-Fi|Thriller', 5);
insert into movie (title, genre, review) values ('Face', 'Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Astro Boy', 'Action|Animation|Children|Sci-Fi', 2);
insert into movie (title, genre, review) values ('EDtv', 'Comedy', 1);
insert into movie (title, genre, review) values ('Reagan', 'Documentary', 3);
insert into movie (title, genre, review) values ('Abbott and Costello in Hollywood', 'Comedy', 2);
insert into movie (title, genre, review) values ('North & South', 'Drama|Romance', 5);
insert into movie (title, genre, review) values ('All at Sea', 'Comedy', 5);
insert into movie (title, genre, review) values ('Our Song', 'Drama', 1);
insert into movie (title, genre, review) values ('Aurora Borealis', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Detective, The (C+ jing taam)', 'Drama|Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('Much Ado About Nothing', 'Comedy|Drama|Romance', 2);
insert into movie (title, genre, review) values ('It Happened Tomorrow', 'Comedy|Fantasy', 2);
insert into movie (title, genre, review) values ('Hijacking, A (Kapringen)', 'Drama|Thriller', 2);
insert into movie (title, genre, review) values ('About Elly (Darbareye Elly)', 'Drama|Mystery', 3);
insert into movie (title, genre, review) values ('Fine, Totally Fine (Zenzen Daijobu)', 'Comedy', 2);
insert into movie (title, genre, review) values ('Twin Dragons (Shuang long hui)', 'Action|Comedy', 1);
insert into movie (title, genre, review) values ('Ballplayer: Pelotero', 'Documentary|Drama', 4);
insert into movie (title, genre, review) values ('Hawaii', 'Romance', 4);
insert into movie (title, genre, review) values ('Dear White People', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Iceman Tapes: Conversations with a Killer, The', 'Crime|Documentary', 3);
insert into movie (title, genre, review) values ('Night in Old Mexico, A', 'Drama|Western', 3);
insert into movie (title, genre, review) values ('Unfinished Business', 'Comedy', 5);
insert into movie (title, genre, review) values ('Genghis Khan', 'Adventure|Drama|War', 4);
insert into movie (title, genre, review) values ('Grande école', 'Drama', 1);
insert into movie (title, genre, review) values ('Firewalker', 'Adventure', 3);
insert into movie (title, genre, review) values ('Phoenix', 'Crime|Drama', 1);
insert into movie (title, genre, review) values ('Decline of Western Civilization, The', 'Documentary|Musical', 3);
insert into movie (title, genre, review) values ('Freakin'' Beautiful World (Sairaan kaunis maailma)', 'Drama', 4);
insert into movie (title, genre, review) values ('Employees'' Entrance', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Sneakers', 'Action|Comedy|Crime|Drama|Sci-Fi', 4);
insert into movie (title, genre, review) values ('City Hall', 'Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Our Fathers', 'Drama', 5);
insert into movie (title, genre, review) values ('Vanishing on 7th Street', 'Horror|Mystery|Thriller', 5);
insert into movie (title, genre, review) values ('American Madness', 'Drama', 5);
insert into movie (title, genre, review) values ('Katy Perry: Part of Me', 'Documentary|Drama', 1);
insert into movie (title, genre, review) values ('Love and Other Troubles', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Story of Maths, The', 'Documentary', 1);
insert into movie (title, genre, review) values ('Toast', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Elephant White', 'Action|Crime|Thriller', 2);
insert into movie (title, genre, review) values ('Won Ton Ton: The Dog Who Saved Hollywood', 'Comedy', 2);
insert into movie (title, genre, review) values ('Badmaash Company', 'Comedy|Crime|Drama', 4);
insert into movie (title, genre, review) values ('Wild Parrots of Telegraph Hill, The', 'Documentary', 1);
insert into movie (title, genre, review) values ('Young Adult', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Raiders of the Lost Ark: The Adaptation', 'Action|Adventure|Thriller', 2);
insert into movie (title, genre, review) values ('Alien Predator (Mutant II) (Falling, The)', 'Drama|Horror|Sci-Fi', 4);
insert into movie (title, genre, review) values ('Pillow of Death', 'Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('Return to Oz', 'Adventure|Children|Fantasy', 5);
insert into movie (title, genre, review) values ('Jungle Book of Regulations, A (Nie Ma Rozy Bez Ognia)', 'Comedy', 4);
insert into movie (title, genre, review) values ('Dr. Jekyll and Mr. Hyde', 'Drama|Horror', 5);
insert into movie (title, genre, review) values ('Seventh Seal, The (Sjunde inseglet, Det)', 'Drama', 3);
insert into movie (title, genre, review) values ('Bookies', 'Comedy|Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Wild Is the Wind', 'Drama', 2);
insert into movie (title, genre, review) values ('Silence of the Sea, The (Le silence de la mer)', 'Drama|Romance|War', 3);
insert into movie (title, genre, review) values ('Orlando', 'Drama|Fantasy|Romance', 2);
insert into movie (title, genre, review) values ('Crazies, The', 'Action|Drama|Horror|Sci-Fi|Thriller', 2);
insert into movie (title, genre, review) values ('Spend It All', 'Documentary', 2);
insert into movie (title, genre, review) values ('Life Is What You Make It (Linha de Passe)', 'Drama', 3);
insert into movie (title, genre, review) values ('Lowlands (Tiefland)', 'Drama', 5);
insert into movie (title, genre, review) values ('House of Dracula', 'Horror', 5);
insert into movie (title, genre, review) values ('La montaña rusa', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('This Is Elvis', 'Documentary|Drama|Musical', 3);
insert into movie (title, genre, review) values ('Love Movie, The (Rakkauselokuva)', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('Hedd Wyn', 'Drama|Romance|War', 3);
insert into movie (title, genre, review) values ('Terminal Velocity', 'Action|Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('Otakus in Love', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Remember Sunday', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Trance', 'Crime|Thriller', 1);
insert into movie (title, genre, review) values ('Moebius Redux: A Life in Pictures', 'Documentary', 4);
insert into movie (title, genre, review) values ('7 Dollars on the Red (Sette dollari sul rosso)', 'Western', 1);
insert into movie (title, genre, review) values ('Brainstorm', 'Sci-Fi|Thriller', 2);
insert into movie (title, genre, review) values ('Antitrust', 'Crime|Drama|Thriller', 2);
insert into movie (title, genre, review) values ('Osmosis Jones', 'Action|Animation|Comedy|Crime|Drama|Romance|Thriller', 4);
insert into movie (title, genre, review) values ('Diary of a Country Priest (Journal d''un curé de campagne)', 'Drama', 4);
insert into movie (title, genre, review) values ('Tarzan''s Magic Fountain', 'Action|Adventure|Fantasy|Romance', 3);
insert into movie (title, genre, review) values ('Sound of Noise', 'Comedy|Crime|Musical', 4);
insert into movie (title, genre, review) values ('Starry starry night (Xing kong)', 'Children|Drama|Fantasy', 3);
insert into movie (title, genre, review) values ('Sybil', 'Drama', 2);
insert into movie (title, genre, review) values ('Time for Killing, A', 'Western', 1);
insert into movie (title, genre, review) values ('Beach Party', 'Comedy', 2);
insert into movie (title, genre, review) values ('Eyes Wide Open (Einayim Petukhoth)', 'Drama', 2);
insert into movie (title, genre, review) values ('Map of the Human Heart', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Day They Robbed the Bank of England, The', 'Crime|Drama', 4);
insert into movie (title, genre, review) values ('Rollo and the Woods Sprite (Rölli ja metsänhenki)', 'Children|Fantasy', 2);
insert into movie (title, genre, review) values ('Escort, The (Scorta, La)', 'Crime|Thriller', 2);
insert into movie (title, genre, review) values ('Exodus: Gods and Kings', 'Action|Adventure|Drama', 5);
insert into movie (title, genre, review) values ('Dead Man on Campus', 'Comedy', 5);
insert into movie (title, genre, review) values ('Me and Orson Welles', 'Drama', 4);
insert into movie (title, genre, review) values ('Whisper of the Heart (Mimi wo sumaseba)', 'Animation|Drama|Romance', 1);
insert into movie (title, genre, review) values ('Ethel', 'Documentary', 4);
insert into movie (title, genre, review) values ('Rocking Horse Winner, The', 'Drama|Horror', 4);
insert into movie (title, genre, review) values ('Slaughter', 'Horror|Thriller', 1);
insert into movie (title, genre, review) values ('Inserts', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('No Logo', 'Documentary', 3);
insert into movie (title, genre, review) values ('Thunderpants', 'Children|Comedy|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Strangler, The', 'Horror', 5);
insert into movie (title, genre, review) values ('Hunting and Gathering (Ensemble, c''est tout)', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Johnny Cash at Folsom Prison', 'Documentary', 4);
insert into movie (title, genre, review) values ('Splendor', 'Comedy', 1);
insert into movie (title, genre, review) values ('Alien³ (a.k.a. Alien 3)', 'Action|Horror|Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values ('Speed Racer', 'Action|Children|Sci-Fi|IMAX', 1);
insert into movie (title, genre, review) values ('Dreaming of Joseph Lees', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('September', 'Drama', 3);
insert into movie (title, genre, review) values ('R', 'Drama', 5);
insert into movie (title, genre, review) values ('Lucky 7', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values ('Christmas Eve', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('August Rush', 'Drama|Musical', 4);
insert into movie (title, genre, review) values ('Endangered Species', 'Mystery|Sci-Fi|Thriller', 2);
insert into movie (title, genre, review) values ('Godfather, The', 'Crime|Drama', 2);
insert into movie (title, genre, review) values ('Police Story (Ging chaat goo si)', 'Action|Comedy|Crime|Thriller', 2);
insert into movie (title, genre, review) values ('Django the Bastard (Strangers Gundown, The) (Django il bastardo)', 'Action|Thriller|Western', 2);
insert into movie (title, genre, review) values ('Beauty and the Beast: The Enchanted Christmas', 'Animation|Children|Fantasy|Musical', 5);
insert into movie (title, genre, review) values ('You''re a Good Man, Charlie Brown', 'Animation|Comedy|Musical', 3);
insert into movie (title, genre, review) values ('Billy Blazes, Esq.', 'Comedy|Western', 4);
insert into movie (title, genre, review) values ('Powder Room', 'Comedy', 1);
insert into movie (title, genre, review) values ('Welcome Home, Roscoe Jenkins', 'Comedy', 4);
insert into movie (title, genre, review) values ('Hotel Transylvania', 'Animation|Children|Comedy', 2);
insert into movie (title, genre, review) values ('Zapped!', 'Comedy|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Jesus Henry Christ', 'Comedy', 3);
insert into movie (title, genre, review) values ('The Two Policemen', 'Comedy', 2);
insert into movie (title, genre, review) values ('Summer of ''42', 'Drama', 3);
insert into movie (title, genre, review) values ('Get Low', 'Comedy|Drama|Mystery', 1);
insert into movie (title, genre, review) values ('American Horror House (Sorority Horror House)', 'Horror', 1);
insert into movie (title, genre, review) values ('Liar''s Dice', 'Adventure|Children|Drama', 2);
insert into movie (title, genre, review) values ('Darfur Now', 'Documentary', 4);
insert into movie (title, genre, review) values ('Comfort and Joy', 'Comedy', 2);
insert into movie (title, genre, review) values ('Big Bird Cage, The', 'Action', 1);
insert into movie (title, genre, review) values ('That Certain Summer', 'Drama', 3);
insert into movie (title, genre, review) values ('Koyaanisqatsi (a.k.a. Koyaanisqatsi: Life Out of Balance)', 'Documentary', 3);
insert into movie (title, genre, review) values ('The Magnificent Gladiator', 'Action|Adventure|Drama', 3);
insert into movie (title, genre, review) values ('Reuben, Reuben', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The', 'Adventure|Children|Fantasy', 1);
insert into movie (title, genre, review) values ('Frank and Ollie', 'Documentary', 2);
insert into movie (title, genre, review) values ('Same River Twice, The', 'Documentary', 2);
insert into movie (title, genre, review) values ('Attack of the 50ft Cheerleader', 'Comedy', 1);
insert into movie (title, genre, review) values ('Day of Wrath (Vredens dag)', 'Drama', 5);
insert into movie (title, genre, review) values ('Jolene', 'Drama', 2);
insert into movie (title, genre, review) values ('For Me and My Gal', 'Drama|Musical|Romance', 2);
insert into movie (title, genre, review) values ('Shot in the Dark, A', 'Comedy|Crime|Mystery', 2);
insert into movie (title, genre, review) values ('Steal This Film II', 'Documentary', 3);
insert into movie (title, genre, review) values ('PT 109', 'Drama|War', 3);
insert into movie (title, genre, review) values ('Ghoulies III: Ghoulies Go to College', 'Comedy|Horror', 4);
insert into movie (title, genre, review) values ('Glass Bottom Boat, The', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('Trouble in Paradise', 'Comedy|Romance', 3);
insert into movie (title, genre, review) values ('Oversimplification of Her Beauty, An', 'Animation|Comedy|Drama|Romance', 3);
insert into movie (title, genre, review) values ('Dorian Blues', 'Comedy', 2);
insert into movie (title, genre, review) values ('Pippi on the Run (På rymmen med Pippi Långstrump)', 'Children', 3);
insert into movie (title, genre, review) values ('Intentions of Murder (a.k.a. Murderous Instincts) (Akai satsui)', 'Drama', 2);
insert into movie (title, genre, review) values ('Codebreaker', 'Documentary|Drama', 2);
insert into movie (title, genre, review) values ('Of Unknown Origin', 'Horror', 4);
insert into movie (title, genre, review) values ('My Giant', 'Comedy', 5);
insert into movie (title, genre, review) values ('Jude', 'Drama', 1);
insert into movie (title, genre, review) values ('House That Dripped Blood, The', 'Horror|Mystery', 1);
insert into movie (title, genre, review) values ('Joy Ride 2: Dead Ahead', 'Action|Horror|Thriller', 1);
insert into movie (title, genre, review) values ('Along the Great Divide (Travelers, The)', 'Adventure|Romance|Western', 1);
insert into movie (title, genre, review) values ('One Hour Photo', 'Drama|Thriller', 2);
insert into movie (title, genre, review) values ('Limuzins Janu nakts krasa', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('English Surgeon, The', 'Documentary', 2);
insert into movie (title, genre, review) values ('Mad City', 'Action|Drama', 1);
insert into movie (title, genre, review) values ('Me and you (io e te)', 'Drama', 1);
insert into movie (title, genre, review) values ('Shadow of Angels (Schatten der Engel)', 'Drama', 4);
insert into movie (title, genre, review) values ('Nutcracker, The', 'Children|Fantasy|Musical', 2);
insert into movie (title, genre, review) values ('Whatever It Takes', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Demon Seed', 'Horror|Sci-Fi|Thriller', 1);
insert into movie (title, genre, review) values ('The Anomaly', 'Action|Sci-Fi|Thriller', 5);
insert into movie (title, genre, review) values ('Rebirth', 'Documentary', 3);
insert into movie (title, genre, review) values ('Destroy All Monsters (Kaijû sôshingeki)', 'Action|Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values ('Phoebe in Wonderland', 'Drama|Fantasy', 3);
insert into movie (title, genre, review) values ('Entertainer, The', 'Drama', 1);
insert into movie (title, genre, review) values ('Brown''s Requiem', 'Drama', 4);
insert into movie (title, genre, review) values ('Nazi Officer''s Wife, The', 'Documentary|Drama|War', 4);
insert into movie (title, genre, review) values ('Last of the Red Hot Lovers', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('Passenger Side', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Cabinet of Dr. Caligari, The (Cabinet des Dr. Caligari., Das)', 'Crime|Fantasy|Horror', 5);
insert into movie (title, genre, review) values ('Duck, You Sucker (a.k.a. Fistful of Dynamite, A) (Giù la testa)', 'Action|Adventure|War|Western', 4);
insert into movie (title, genre, review) values ('Woman Rebels, A (Portrait of a Rebel)', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Rampage at Apache Wells', 'Adventure|Western', 2);
insert into movie (title, genre, review) values ('Northeast', 'Drama', 5);
insert into movie (title, genre, review) values ('Madame Sousatzka', 'Drama', 4);
insert into movie (title, genre, review) values ('Girls, Les', 'Musical', 3);
insert into movie (title, genre, review) values ('Tonight and Every Night', 'Musical', 3);
insert into movie (title, genre, review) values ('Girls Town', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Bedtime Stories', 'Adventure|Children|Comedy', 1);
insert into movie (title, genre, review) values ('Wild Hogs', 'Adventure|Comedy', 2);
insert into movie (title, genre, review) values ('Fighting Seabees, The', 'Action|Drama|War', 2);
insert into movie (title, genre, review) values ('Game Over', 'Crime|Drama|Thriller', 2);
insert into movie (title, genre, review) values ('Secret, The', 'Documentary', 1);
insert into movie (title, genre, review) values ('Lotta 2: Lotta flyttar hemifrån', 'Children', 1);
insert into movie (title, genre, review) values ('Disturbia', 'Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Gus', 'Children|Comedy', 1);
insert into movie (title, genre, review) values ('Third Wave, The (Tredje vågen, Den)', 'Action|Thriller', 3);
insert into movie (title, genre, review) values ('Overnighters, The', 'Documentary|Drama', 5);
insert into movie (title, genre, review) values ('Hot Spot, The', 'Crime|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Live Free or Die', 'Comedy|Crime', 2);
insert into movie (title, genre, review) values ('Sea Inside, The (Mar adentro)', 'Drama', 3);
insert into movie (title, genre, review) values ('One Point O', 'Drama|Mystery|Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values ('Sierra, La', 'Documentary', 2);
insert into movie (title, genre, review) values ('Fraternity Vacation', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('Truth About Charlie, The', 'Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('Palais royal !', 'Comedy', 3);
insert into movie (title, genre, review) values ('New York Ripper, The (Squartatore di New York, Lo)', 'Crime|Horror|Mystery|Thriller', 2);
insert into movie (title, genre, review) values ('Just Go with It', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Pokémon the Movie: White - Victini and Zekrom', 'Animation', 2);
insert into movie (title, genre, review) values ('Monterey Pop', 'Documentary|Musical', 1);
insert into movie (title, genre, review) values ('Blue', 'Romance|Western', 4);
insert into movie (title, genre, review) values ('Wasabi', 'Action|Comedy|Crime|Drama|Thriller', 1);
insert into movie (title, genre, review) values ('Lady in Number 6: Music Saved My Life, The', 'Documentary|Drama', 1);
insert into movie (title, genre, review) values ('Desert Trail, The', 'Western', 4);
insert into movie (title, genre, review) values ('Woman That Dreamed About a Man, The (Kvinden der drømte om en mand)', 'Drama', 4);
insert into movie (title, genre, review) values ('A Mulher Invisível', 'Comedy', 1);
insert into movie (title, genre, review) values ('Left Behind', 'Action|Sci-Fi|Thriller', 1);
insert into movie (title, genre, review) values ('D2: The Mighty Ducks', 'Children|Comedy', 5);
insert into movie (title, genre, review) values ('Arch of Triumph', 'Drama|Romance|War', 5);
insert into movie (title, genre, review) values ('Whiteout', 'Action|Crime|Drama|Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('Ugetsu (Ugetsu monogatari)', 'Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Woman Rebels, A (Portrait of a Rebel)', 'Drama|Romance', 5);
insert into movie (title, genre, review) values ('Hans Christian Andersen', 'Children|Musical', 4);
insert into movie (title, genre, review) values ('Betty', 'Drama', 2);
insert into movie (title, genre, review) values ('Defending Your Life', 'Comedy|Drama|Fantasy|Romance', 5);
insert into movie (title, genre, review) values ('Rebecca of Sunnybrook Farm', 'Children|Comedy|Drama|Musical', 5);
insert into movie (title, genre, review) values ('The Russian Novel', 'Drama', 4);
insert into movie (title, genre, review) values ('Ascension', 'Drama|Sci-Fi', 4);
insert into movie (title, genre, review) values ('Dallas 362', 'Drama', 2);
insert into movie (title, genre, review) values ('Marrying Kind, The', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Transsiberian', 'Crime|Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Rapt', 'Drama', 1);
insert into movie (title, genre, review) values ('Lilla Jönssonligan och Cornflakeskuppen', 'Children|Comedy', 3);
insert into movie (title, genre, review) values ('Deadly Spawn, The', 'Horror|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Beauty and the Beast (Beauty and the Beasts: A Dark Tale)', 'Fantasy', 2);
insert into movie (title, genre, review) values ('Dead Rising: Watchtower', 'Action|Horror|Thriller', 5);
insert into movie (title, genre, review) values ('Bullfighter and the Lady', 'Action|Drama|Romance', 3);
insert into movie (title, genre, review) values ('Wonderful World of the Brothers Grimm, The', 'Adventure|Animation|Children|Comedy|Drama|Fantasy|Musical|Romance', 3);
insert into movie (title, genre, review) values ('File on Thelma Jordan, The', 'Crime|Drama|Film-Noir|Mystery', 3);
insert into movie (title, genre, review) values ('Uncovered', 'Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('August', 'Drama', 3);
insert into movie (title, genre, review) values ('Dottie Gets Spanked', 'Drama', 4);
insert into movie (title, genre, review) values ('Miss March', 'Comedy', 2);
insert into movie (title, genre, review) values ('Maltese Falcon, The', 'Film-Noir|Mystery', 4);
insert into movie (title, genre, review) values ('Young Doctors in Love', 'Comedy', 4);
insert into movie (title, genre, review) values ('Confessions of a Window Cleaner', 'Comedy', 3);
insert into movie (title, genre, review) values ('ATL', 'Drama', 3);
insert into movie (title, genre, review) values ('The Periwig-Maker', 'Animation', 2);
insert into movie (title, genre, review) values ('Moon 44', 'Action|Film-Noir|Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values ('Animated Motion: Part 5', 'Animation|Documentary', 2);
insert into movie (title, genre, review) values ('Remote Control', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Interstate 60', 'Adventure|Comedy|Drama|Fantasy|Mystery|Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values ('Taste of Tea, The (Cha no aji)', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('Effie Gray', 'Drama', 2);
insert into movie (title, genre, review) values ('Running With Scissors', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Harlan County U.S.A.', 'Documentary', 2);
insert into movie (title, genre, review) values ('Consequences of Love, The (Conseguenze dell''amore, Le)', 'Crime|Drama', 3);
insert into movie (title, genre, review) values ('Yol (a.k.a. The Way)', 'Drama', 5);
insert into movie (title, genre, review) values ('Mega Piranha', 'Action|Adventure|Horror|Sci-Fi', 4);
insert into movie (title, genre, review) values ('Ten Skies', 'Documentary', 2);
insert into movie (title, genre, review) values ('Byzantium', 'Drama|Fantasy|Thriller', 4);
insert into movie (title, genre, review) values ('Rat', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values ('Futurama: The Beast with a Billion Backs', 'Action|Animation|Comedy|Romance|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Quo Vadis', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Pudana Last of the Line (Sukunsa viimeinen)', 'Drama', 5);
insert into movie (title, genre, review) values ('Busses Roar (Buses Roar)', 'Drama|Romance|War', 2);
insert into movie (title, genre, review) values ('Big Easy, The', 'Action|Crime|Mystery|Romance|Thriller', 5);
insert into movie (title, genre, review) values ('Don''t Worry, I''m Fine (Je vais bien, ne t''en fais pas)', 'Drama', 2);
insert into movie (title, genre, review) values ('Serrallonga', 'Adventure|Drama', 1);
insert into movie (title, genre, review) values ('Hunger Games: Catching Fire, The', 'Action|Adventure|Sci-Fi|IMAX', 1);
insert into movie (title, genre, review) values ('Opening Night', 'Drama', 5);
insert into movie (title, genre, review) values ('Story of Maths, The', 'Documentary', 5);
insert into movie (title, genre, review) values ('Killing of John Lennon, The', 'Drama', 4);
insert into movie (title, genre, review) values ('Gideon''s Army', 'Documentary', 4);
insert into movie (title, genre, review) values ('Cool as Ice', 'Drama', 3);
insert into movie (title, genre, review) values ('Wooden Crosses (Les croix de bois)', 'Drama|War', 5);
insert into movie (title, genre, review) values ('Salsa', 'Musical|Romance', 4);
insert into movie (title, genre, review) values ('La montaña rusa', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values ('Resident Evil: Degeneration (Baiohazâdo: Dijenerêshon)', 'Animation|Horror', 3);
insert into movie (title, genre, review) values ('Fidanzati, I (Fiances, The)', 'Drama', 2);
insert into movie (title, genre, review) values ('Beast of Yucca Flats, The', 'Horror|Sci-Fi', 2);
insert into movie (title, genre, review) values ('Man - Woman Wanted (Poszukiwany, poszukiwana)', 'Comedy', 1);
insert into movie (title, genre, review) values ('Martyrs', 'Horror', 1);
insert into movie (title, genre, review) values ('Eye In The Sky (Gun chung)', 'Crime|Thriller', 1);
insert into movie (title, genre, review) values ('Secretary', 'Comedy|Drama|Romance', 1);
insert into movie (title, genre, review) values ('Green Street Hooligans 2', 'Action|Crime|Drama', 5);
insert into movie (title, genre, review) values ('O', 'Drama', 1);
insert into movie (title, genre, review) values ('Atalante, L''', 'Comedy|Drama|Romance', 3);
insert into movie (title, genre, review) values ('Clerks', 'Comedy', 1);
insert into movie (title, genre, review) values ('The Land Before Time IX: Journey to the Big Water', 'Adventure|Animation|Children', 5);
insert into movie (title, genre, review) values ('Fire Over England', 'Adventure|Romance|War', 1);
insert into movie (title, genre, review) values ('My Beautiful Laundrette', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('The Gardener', '(no genres listed)', 1);
insert into movie (title, genre, review) values ('Fine Mess, A', 'Comedy', 5);
insert into movie (title, genre, review) values ('Kabhi Haan Kabhi Naa', 'Comedy|Drama|Musical|Romance', 4);
insert into movie (title, genre, review) values ('Carriage to Vienna', 'Drama|War', 1);
insert into movie (title, genre, review) values ('Time Machine, The', 'Action|Adventure|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Adventures of Felix, The (a.k.a. Funny Felix) (Drôle de Félix)', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Killing Zoe', 'Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Never Sleep Again: The Elm Street Legacy', 'Documentary', 3);
insert into movie (title, genre, review) values ('Human Behavior Experiments, The', 'Documentary', 2);
insert into movie (title, genre, review) values ('Pilgrimage', 'Drama', 1);
insert into movie (title, genre, review) values ('Life of a King', 'Drama', 1);
insert into movie (title, genre, review) values ('To Hell and Back', 'Action|Drama|War', 5);
insert into movie (title, genre, review) values ('Balls of Fury', 'Comedy', 5);
insert into movie (title, genre, review) values ('Transporter 2', 'Action|Crime|Thriller', 5);
insert into movie (title, genre, review) values ('Two Jakes, The', 'Drama', 5);
insert into movie (title, genre, review) values ('Sh! The Octopus', 'Comedy|Mystery', 3);
insert into movie (title, genre, review) values ('Stormheart', 'Children|Drama', 1);
insert into movie (title, genre, review) values ('Caliber 9', 'Action|Crime|Thriller', 3);
insert into movie (title, genre, review) values ('If You Don''t Stop It... You''ll Go Blind!!!', 'Comedy', 1);
insert into movie (title, genre, review) values ('Fugly!', 'Comedy', 3);
insert into movie (title, genre, review) values ('Bamboozled', 'Comedy', 5);
insert into movie (title, genre, review) values ('Pelican Brief, The', 'Crime|Drama|Mystery|Romance|Thriller', 2);
insert into movie (title, genre, review) values ('Man''s Best Friend', 'Horror|Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values ('Los Bandoleros', 'Action|Drama', 1);
insert into movie (title, genre, review) values ('84 Charing Cross Road', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Hotel New Hampshire, The', 'Drama', 3);
insert into movie (title, genre, review) values ('If Winter Comes', 'Drama', 2);
insert into movie (title, genre, review) values ('Air Bud', 'Children|Comedy', 4);
insert into movie (title, genre, review) values ('Scary Movie 4', 'Comedy|Horror', 3);
insert into movie (title, genre, review) values ('Lord, Save Us from Your Followers', 'Documentary', 3);
insert into movie (title, genre, review) values ('In Vogue: The Editor?s Eye', 'Documentary', 1);
insert into movie (title, genre, review) values ('Killer Joe', 'Crime|Thriller', 4);
insert into movie (title, genre, review) values ('Secret Adventures of Tom Thumb, The', 'Adventure|Animation', 4);
insert into movie (title, genre, review) values ('Land, The (Al-ard)', 'Drama', 1);
insert into movie (title, genre, review) values ('Saving Mr. Banks', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Citizen Kane', 'Drama|Mystery', 1);
insert into movie (title, genre, review) values ('Race with the Devil', 'Action|Horror|Mystery', 2);
insert into movie (title, genre, review) values ('Don''t Look Now', 'Drama|Horror|Thriller', 1);
insert into movie (title, genre, review) values ('Feast of All Saints', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Spring Breakers', 'Comedy|Crime|Drama', 2);
insert into movie (title, genre, review) values ('Little Men', 'Drama', 5);
insert into movie (title, genre, review) values ('LUV', 'Drama', 1);
insert into movie (title, genre, review) values ('Animal Room', 'Drama|Thriller', 3);
insert into movie (title, genre, review) values ('La dama boba', 'Comedy', 2);
insert into movie (title, genre, review) values ('Above the Rim', 'Crime|Drama', 2);
insert into movie (title, genre, review) values ('Date with an Angel', 'Comedy|Fantasy|Romance', 1);
insert into movie (title, genre, review) values ('2 Fast 2 Furious (Fast and the Furious 2, The)', 'Action|Crime|Thriller', 5);
insert into movie (title, genre, review) values ('Love Wrecked', 'Comedy|Romance', 2);
insert into movie (title, genre, review) values ('Ten Violent Women', 'Action|Drama', 4);
insert into movie (title, genre, review) values ('Thief of Bagdad, The', 'Action|Adventure|Fantasy', 5);
insert into movie (title, genre, review) values ('Change of Plans (Le code a changé)', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('How to Deal', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Broken Windows', 'Drama', 4);
insert into movie (title, genre, review) values ('Ichi', 'Action', 2);
insert into movie (title, genre, review) values ('Farewell, Home Sweet Home (Adieu, plancher des vaches!)', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Tin Toy', 'Animation|Children', 4);
insert into movie (title, genre, review) values ('Incredible Melting Man, The', 'Horror|Sci-Fi', 2);
insert into movie (title, genre, review) values ('Beverly Hills Chihuahua', 'Adventure|Children|Comedy', 4);
insert into movie (title, genre, review) values ('Fantastic Four, The', 'Action|Adventure|Fantasy|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Nobody''s Children (I figli di nessuno)', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Getaway, The', 'Action|Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Duel in the Sun', 'Western', 1);
insert into movie (title, genre, review) values ('Candy Snatchers, The', 'Crime|Thriller', 1);
insert into movie (title, genre, review) values ('Far Horizons, The', 'Western', 2);
insert into movie (title, genre, review) values ('Capricious Summer (Rozmarné léto)', 'Comedy', 5);
insert into movie (title, genre, review) values ('Don''s Plum', 'Drama', 1);
insert into movie (title, genre, review) values ('Assault on Wall Street ', 'Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Summer Holiday', 'Musical|Romance', 1);
insert into movie (title, genre, review) values ('Separation City', 'Comedy|Drama|Romance', 3);
insert into movie (title, genre, review) values ('Whistle Blower, The', 'Thriller', 4);
insert into movie (title, genre, review) values ('Celtic Pride', 'Comedy', 2);
insert into movie (title, genre, review) values ('Recess: School''s Out', 'Animation|Children', 3);
insert into movie (title, genre, review) values ('Get Carter', 'Action|Drama|Thriller', 1);
insert into movie (title, genre, review) values ('Lightspeed', 'Action|Fantasy|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Two Days, One Night (Deux jours, une nuit)', 'Drama', 4);
insert into movie (title, genre, review) values ('Heartbreak Kid, The', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Sons of Katie Elder', 'Western', 4);
insert into movie (title, genre, review) values ('My Old Lady', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Driver, The', 'Action|Crime|Film-Noir', 5);
insert into movie (title, genre, review) values ('42', 'Drama', 5);
insert into movie (title, genre, review) values ('Rock of Ages', 'Comedy|Drama|Musical|IMAX', 2);
insert into movie (title, genre, review) values ('How the Myth Was Made: A Study of Robert Flaherty''s Man of Aran', 'Documentary', 4);
insert into movie (title, genre, review) values ('Reality', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Midnight (Primeiro Dia, O)', 'Drama', 5);
insert into movie (title, genre, review) values ('Duck Soup', 'Comedy|Musical|War', 3);
insert into movie (title, genre, review) values ('Operación Cannabis', 'Action|Adventure|Comedy|Crime', 4);
insert into movie (title, genre, review) values ('Quartet', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Terminator, The', 'Action|Sci-Fi|Thriller', 2);
insert into movie (title, genre, review) values ('Dark Angel (I Come in Peace)', 'Action|Horror|Sci-Fi|Thriller', 5);
insert into movie (title, genre, review) values ('I Never Sang for My Father', 'Drama', 1);
insert into movie (title, genre, review) values ('6 Bullets', 'Action|Crime|Thriller', 4);
insert into movie (title, genre, review) values ('Neighbors', 'Comedy', 2);
insert into movie (title, genre, review) values ('Turning, The', 'Drama', 5);
insert into movie (title, genre, review) values ('Happy Tears', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Napoleon and Samantha', 'Adventure|Drama', 3);
insert into movie (title, genre, review) values ('Asier ETA biok', 'Documentary', 1);
insert into movie (title, genre, review) values ('Route Irish', 'Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Grave Secrets (Silent Screams)', 'Horror', 3);
insert into movie (title, genre, review) values ('Haunting at Silver Falls, A', 'Horror|Thriller', 4);
insert into movie (title, genre, review) values ('Romasanta: The Werewolf Hunt', 'Drama|Horror|Mystery', 5);
insert into movie (title, genre, review) values ('Dead Presidents', 'Action|Crime|Drama', 1);
insert into movie (title, genre, review) values ('Bombardier', 'Drama|War', 1);
insert into movie (title, genre, review) values ('Banger Sisters, The', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Day of the Dead 2: Contagium', 'Horror|Sci-Fi', 4);
insert into movie (title, genre, review) values ('Cast a Giant Shadow', 'Adventure|War', 1);
insert into movie (title, genre, review) values ('True Confessions', 'Crime|Drama', 3);
insert into movie (title, genre, review) values ('Desperate Measures', 'Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('I Saw the Sun (Günesi gördüm)', 'Drama', 1);
insert into movie (title, genre, review) values ('Jimi Hendrix: Hear My Train A Comin''', 'Documentary', 2);
insert into movie (title, genre, review) values ('Bogowie', 'Drama', 1);
insert into movie (title, genre, review) values ('External Affairs', 'Drama', 2);
insert into movie (title, genre, review) values ('Aaron Loves Angela', 'Comedy|Drama|Romance|Thriller', 2);
insert into movie (title, genre, review) values ('Treasure Hunter, The (Ci ling)', 'Action|Adventure|Fantasy|Romance|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Games', 'Thriller', 2);
insert into movie (title, genre, review) values ('Wheelmen', 'Comedy', 4);
insert into movie (title, genre, review) values ('Hercules in New York', 'Action|Comedy|Fantasy', 4);
insert into movie (title, genre, review) values ('Mystery of the Third Planet, The (Tayna tretey planety)', 'Adventure|Animation|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Body Heat', 'Crime|Thriller', 5);
insert into movie (title, genre, review) values ('London After Midnight', 'Drama|Horror', 1);
insert into movie (title, genre, review) values ('Return of the Prodigal Son, The (Návrat ztraceného syna)', 'Drama', 1);
insert into movie (title, genre, review) values ('Jack Ryan: Shadow Recruit', 'Action|Drama|Thriller|IMAX', 5);
insert into movie (title, genre, review) values ('Advanced Style', 'Comedy|Documentary|Drama', 3);
insert into movie (title, genre, review) values ('Carry on Behind', 'Comedy', 3);
insert into movie (title, genre, review) values ('Asterix & Obelix: God Save Britannia (Astérix et Obélix: Au service de Sa Majesté)', 'Adventure|Comedy', 4);
insert into movie (title, genre, review) values ('Cochochi', 'Drama', 5);
insert into movie (title, genre, review) values ('Mister Magoo''s Christmas Carol', 'Animation|Children|Comedy|Drama|Fantasy|Musical', 2);
insert into movie (title, genre, review) values ('Warped Ones, The (Kyonetsu no kisetsu)', 'Drama', 4);
insert into movie (title, genre, review) values ('Chemical Brothers: Don''t Think, The', 'Musical', 3);
insert into movie (title, genre, review) values ('Still Life', 'Drama', 1);
insert into movie (title, genre, review) values ('Eila, Rampe and Likka', 'Comedy', 3);
insert into movie (title, genre, review) values ('...And God Spoke', 'Comedy', 3);
insert into movie (title, genre, review) values ('Immigrants (L.A. Dolce Vita)', 'Animation', 1);
insert into movie (title, genre, review) values ('Kamchatka', 'Drama', 1);
insert into movie (title, genre, review) values ('Blade Runner', 'Action|Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values ('EMR', 'Thriller', 4);
insert into movie (title, genre, review) values ('Mercy ', 'Horror|Thriller', 2);
insert into movie (title, genre, review) values ('Land Girls, The', 'Drama|War', 2);
insert into movie (title, genre, review) values ('Growth', 'Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values ('Thief Lord, The', 'Adventure|Children|Fantasy', 2);
insert into movie (title, genre, review) values ('Tarda estate', 'Drama', 3);
insert into movie (title, genre, review) values ('Camp', 'Comedy|Musical', 2);
insert into movie (title, genre, review) values ('Attila (Attila the Hun)', 'Action|Adventure|Drama|War', 1);
insert into movie (title, genre, review) values ('Cutie and the Boxer', 'Documentary', 2);
insert into movie (title, genre, review) values ('Great Freedom No. 7 (Port of Freedom) (Große Freiheit Nr. 7)', 'Drama|Musical|Romance', 4);
insert into movie (title, genre, review) values ('Chance', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('All About Steve', 'Comedy', 3);
insert into movie (title, genre, review) values ('Kedma', 'Drama|War', 2);
insert into movie (title, genre, review) values ('Badlanders, The', 'Romance|Western', 3);
insert into movie (title, genre, review) values ('Age of Heroes', 'Action|Adventure|Drama|Thriller|War', 2);
insert into movie (title, genre, review) values ('Coal Miner''s Daughter', 'Drama', 1);
insert into movie (title, genre, review) values ('Any Questions for Ben?', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('RoboCop 2', 'Action|Crime|Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values ('Doulos, Le', 'Crime|Thriller', 3);
insert into movie (title, genre, review) values ('Slave Girls (Prehistoric Women)', 'Adventure|Fantasy', 1);
insert into movie (title, genre, review) values ('Thin Blue Line, The', 'Documentary', 4);
insert into movie (title, genre, review) values ('Mrs. Parkington', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Murderer Lives at Number 21, The (L''assassin habite... au 21)', 'Comedy|Mystery|Thriller', 3);
insert into movie (title, genre, review) values ('At Berkeley', 'Documentary', 1);
insert into movie (title, genre, review) values ('Dirty Dozen: The Deadly Mission', 'Action|Drama|War', 3);
insert into movie (title, genre, review) values ('Loser Takes All, The (O hamenos ta pairnei ola)', 'Action|Adventure|Drama', 1);
insert into movie (title, genre, review) values ('Taxi Hunter (Di shi pan guan)', 'Action', 1);
insert into movie (title, genre, review) values ('For Queen and Country', 'Drama', 5);
insert into movie (title, genre, review) values ('Shot in the Heart', 'Crime|Drama', 4);
insert into movie (title, genre, review) values ('10 Rillington Place', 'Crime|Drama|Thriller', 2);
insert into movie (title, genre, review) values ('Money Train', 'Action|Comedy|Crime|Drama|Thriller', 1);
insert into movie (title, genre, review) values ('Mother and Child', 'Drama', 1);
insert into movie (title, genre, review) values ('Tony Manero', 'Crime|Drama', 1);
insert into movie (title, genre, review) values ('As I Was Moving Ahead Occasionally I Saw Brief Glimpses of Beauty', 'Documentary', 2);
insert into movie (title, genre, review) values ('Torso', 'Horror|Mystery|Thriller', 1);
insert into movie (title, genre, review) values ('Go Get Some Rosemary (Daddy Longlegs)', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Mute Witness', 'Comedy|Horror|Thriller', 5);
insert into movie (title, genre, review) values ('Vuonna 85', 'Comedy', 3);
insert into movie (title, genre, review) values ('Michael Clayton', 'Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Last Detail, The', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('Vuonna 85', 'Comedy', 4);
insert into movie (title, genre, review) values ('Somewhere in Time', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('And Your Mother Too (Y tu mamá también)', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Heartburn', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Mystery on Monster Island', 'Adventure|Comedy', 4);
insert into movie (title, genre, review) values ('Great Bank Hoax, The', 'Comedy|Crime', 2);
insert into movie (title, genre, review) values ('Hello Herman', 'Drama', 2);
insert into movie (title, genre, review) values ('Darling Lili', 'Drama|War', 3);
insert into movie (title, genre, review) values ('Enemies Closer', 'Action|Thriller', 5);
insert into movie (title, genre, review) values ('Ethel', 'Documentary', 3);
insert into movie (title, genre, review) values ('Dragnet', 'Comedy|Crime|Drama', 3);
insert into movie (title, genre, review) values ('Meet Bill', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Station, The (Blutgletscher)', 'Horror', 1);
insert into movie (title, genre, review) values ('Sink or Swim', 'Documentary', 1);
insert into movie (title, genre, review) values ('Premature Burial, The', 'Horror', 1);
insert into movie (title, genre, review) values ('Four Daughters', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Cannibal Holocaust', 'Horror', 3);
insert into movie (title, genre, review) values ('Bad and the Beautiful, The', 'Drama', 1);
insert into movie (title, genre, review) values ('Osama', 'Drama', 5);
insert into movie (title, genre, review) values ('Our Family Wedding', 'Comedy', 4);
insert into movie (title, genre, review) values ('Blackout, The', 'Drama', 4);
insert into movie (title, genre, review) values ('Meet the Spartans', 'Comedy', 5);
insert into movie (title, genre, review) values ('Mission London', 'Comedy', 5);
insert into movie (title, genre, review) values ('Standing Aside, Watching', 'Drama', 3);
insert into movie (title, genre, review) values ('Terror is a Man', 'Horror|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Firstborn', 'Drama|Thriller', 2);
insert into movie (title, genre, review) values ('Hot Rods to Hell', 'Action|Drama|Thriller', 1);
insert into movie (title, genre, review) values ('Good-bye, My Lady', 'Drama', 3);
insert into movie (title, genre, review) values ('Rashomon (Rashômon)', 'Crime|Drama|Mystery', 2);
insert into movie (title, genre, review) values ('Ricky Gervais: Out of England - The Stand-Up Special', 'Comedy', 3);
insert into movie (title, genre, review) values ('Tao of Steve, The', 'Comedy', 2);
insert into movie (title, genre, review) values ('Hotel Chevalier (Part 1 of ''The Darjeeling Limited'')', 'Drama', 1);
insert into movie (title, genre, review) values ('Late Autumn (Man-choo)', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Second Wind (Le deuxième souffle) (Second Breath)', 'Crime|Drama|Film-Noir', 3);
insert into movie (title, genre, review) values ('Sixty Six', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Nô', 'Drama', 4);
insert into movie (title, genre, review) values ('Head of State', 'Comedy', 4);
insert into movie (title, genre, review) values ('By the Law', 'Drama', 5);
insert into movie (title, genre, review) values ('Enough', 'Drama|Thriller', 4);
insert into movie (title, genre, review) values ('Rio Grande', 'Romance|Western', 1);
insert into movie (title, genre, review) values ('The Secret of Dr. Kildare', 'Drama', 5);
insert into movie (title, genre, review) values ('There Goes My Heart', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Night of the Living Dorks', 'Comedy|Horror', 1);
insert into movie (title, genre, review) values ('Jack Brooks: Monster Slayer', 'Action|Comedy|Horror', 2);
insert into movie (title, genre, review) values ('Handful of Dust, A', 'Drama', 5);
insert into movie (title, genre, review) values ('Genocide', 'Documentary', 1);
insert into movie (title, genre, review) values ('Atomic Twister', 'Action|Drama|Sci-Fi', 3);
insert into movie (title, genre, review) values ('I Was a Teenage Zombie', 'Comedy|Horror', 2);
insert into movie (title, genre, review) values ('Alphabet', 'Documentary', 2);
insert into movie (title, genre, review) values ('Tribulation', 'Drama|Sci-Fi|Thriller', 1);
insert into movie (title, genre, review) values ('Bucky Larson: Born to Be a Star', 'Comedy', 2);
insert into movie (title, genre, review) values ('Season''s Greetings', 'Comedy', 5);
insert into movie (title, genre, review) values ('Vinci', 'Comedy|Crime', 5);
insert into movie (title, genre, review) values ('Three Days (Tres días)', 'Crime|Drama|Fantasy', 5);
insert into movie (title, genre, review) values ('Persuasion', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Deadline', 'Mystery|Thriller', 1);
insert into movie (title, genre, review) values ('Texas Rangers', 'Adventure|Western', 2);
insert into movie (title, genre, review) values ('Swamp Women', 'Adventure|Crime|Horror', 2);
insert into movie (title, genre, review) values ('Jacob''s Ladder', 'Horror|Mystery', 5);
insert into movie (title, genre, review) values ('Charlie Chan in the Secret Service', 'Comedy|Crime|Mystery', 4);
insert into movie (title, genre, review) values ('Net Worth', 'Drama', 4);
insert into movie (title, genre, review) values ('State of Emergency', 'Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values ('Cabin in the Woods, The', 'Comedy|Horror|Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values ('This is Martin Bonner', 'Drama', 1);
insert into movie (title, genre, review) values ('Looking for Mr. Goodbar', 'Drama', 3);
insert into movie (title, genre, review) values ('My Side of the Mountain', 'Adventure|Children', 5);
insert into movie (title, genre, review) values ('Blood Simple', 'Crime|Drama|Film-Noir', 3);
insert into movie (title, genre, review) values ('Old Acquaintance', 'Drama', 2);
insert into movie (title, genre, review) values ('Blackbeard, the Pirate', 'Adventure', 1);
insert into movie (title, genre, review) values ('Mannequin 2: On the Move', 'Comedy|Fantasy|Romance', 5);
insert into movie (title, genre, review) values ('Out for Justice', 'Action|Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('The Snow White Murder Case', 'Drama|Mystery', 1);
insert into movie (title, genre, review) values ('Showtime', 'Action|Comedy', 2);
insert into movie (title, genre, review) values ('American Sniper', 'Action|War', 5);
insert into movie (title, genre, review) values ('One in the Chamber', 'Action|Crime|Thriller', 1);
insert into movie (title, genre, review) values ('Public Sex', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Assassination', 'Action|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Cigarette Girl of Mosselprom, The (Papirosnitsa ot Mosselproma)', 'Comedy|Romance', 2);
insert into movie (title, genre, review) values ('Highwaymen', 'Action|Crime|Thriller', 3);
insert into movie (title, genre, review) values ('Beyond the Clouds (Al di là delle nuvole)', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Opportunity Knocks', 'Comedy', 2);
insert into movie (title, genre, review) values ('Hot Shots!', 'Action|Comedy|Romance|War', 2);
insert into movie (title, genre, review) values ('Hillsborough', 'Drama', 2);
insert into movie (title, genre, review) values ('Flight 93', 'Drama', 5);
insert into movie (title, genre, review) values ('Toute la mémoire du monde', 'Documentary', 2);
insert into movie (title, genre, review) values ('Children Shouldn''t Play with Dead Things', 'Horror', 5);
insert into movie (title, genre, review) values ('Liverpool', 'Drama', 5);
insert into movie (title, genre, review) values ('Hiroshima ', 'Documentary', 1);
insert into movie (title, genre, review) values ('Blood Work', 'Crime|Drama|Mystery|Thriller', 2);
insert into movie (title, genre, review) values ('Right Stuff, The', 'Drama', 4);
insert into movie (title, genre, review) values ('Secretary', 'Comedy|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Jet Pilot', 'Drama', 3);
insert into movie (title, genre, review) values ('Seeking Justice', 'Action|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Dragon Ball Z: Super Android 13! (Doragon bôru Z 7: Kyokugen batoru!! San dai sûpâ saiyajin)', 'Action|Adventure|Animation', 5);
insert into movie (title, genre, review) values ('Texas Across the River', 'Comedy|Western', 3);
insert into movie (title, genre, review) values ('Chouga (Shuga)', 'Drama', 3);
insert into movie (title, genre, review) values ('Scarlet Empress, The', 'Drama', 1);
insert into movie (title, genre, review) values ('After Alice (Eye of the Killer)', 'Crime|Drama|Mystery|Thriller', 2);
insert into movie (title, genre, review) values ('Butterfly (La lengua de las mariposas)', 'Drama', 2);
insert into movie (title, genre, review) values ('Brave One, The', 'Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('Class, The (Klass)', 'Drama', 3);
insert into movie (title, genre, review) values ('Crazy/Beautiful', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Thesis (Tesis)', 'Drama|Horror|Thriller', 3);

