--This style is to compliment the schema.sql file
--INSERT INTO movie (genre, review, title, year) VALUES ('Comedy', 1, 'A', 1981);
--INSERT INTO movie (genre, review, title, year) VALUES ('Drama', 2, 'B', 1984);
--INSERT INTO movie (genre, review, title, year) VALUES ('Satire', 3, 'C', 1987);
--INSERT INTO movie (genre, review, title, year) VALUES ('Horror', 4, 'D', 1990);
--INSERT INTO movie (genre, review, title, year) VALUES ('Romance', 5, 'E', 1993);
--INSERT INTO movie (genre, review, title, year) VALUES ('Action', 5, 'Terminator', 1984);

insert into movie (title, genre, review) values (1, 'Rembrandt''s J''accuse', 'Documentary|Mystery', 3);
insert into movie (title, genre, review) values (2, 'Nickelodeon', 'Comedy', 1);
insert into movie (title, genre, review) values (3, 'Kids Are All Right, The', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (4, 'Price of Glory', 'Drama', 4);
insert into movie (title, genre, review) values (5, 'Garden State', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values (6, 'Exposed', 'Drama', 4);
insert into movie (title, genre, review) values (7, 'Cassandra''s Dream', 'Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values (8, 'Luzhin Defence, The', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (9, 'Boarding Gate', 'Thriller', 5);
insert into movie (title, genre, review) values (10, 'Simon Says', 'Horror', 1);
insert into movie (title, genre, review) values (11, 'K-19: The Widowmaker', 'Action|Adventure|Drama|Thriller', 5);
insert into movie (title, genre, review) values (12, 'Trick', 'Comedy|Romance', 2);
insert into movie (title, genre, review) values (13, 'Take, The', 'Crime|Drama', 2);
insert into movie (title, genre, review) values (14, 'Série noire', 'Film-Noir', 3);
insert into movie (title, genre, review) values (15, 'Nothing Like the Holidays', 'Comedy|Drama|Romance', 1);
insert into movie (title, genre, review) values (16, 'Virgin Stripped Bare by Her Bachelors (Oh! Soo-jung)', 'Drama', 4);
insert into movie (title, genre, review) values (17, 'Buona Sera, Mrs. Campbell', 'Comedy', 2);
insert into movie (title, genre, review) values (18, 'Salaam Cinema', 'Comedy|Documentary|Drama', 1);
insert into movie (title, genre, review) values (19, 'Clint Eastwood: Out of the Shadows', 'Documentary', 2);
insert into movie (title, genre, review) values (20, 'Defiance', 'Action|Crime|Drama', 1);
insert into movie (title, genre, review) values (21, 'Kundun', 'Drama', 1);
insert into movie (title, genre, review) values (22, 'Edge of the City', 'Drama|Film-Noir', 2);
insert into movie (title, genre, review) values (23, 'Are We There Yet?', 'Children|Comedy', 1);
insert into movie (title, genre, review) values (24, 'Kiss the Bride', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values (25, 'Ace in the Hole (Big Carnival, The)', 'Drama', 3);
insert into movie (title, genre, review) values (26, 'Pickle, The', 'Comedy', 1);
insert into movie (title, genre, review) values (27, 'Black Like Me', 'Drama', 5);
insert into movie (title, genre, review) values (28, 'Dot and the Whale', 'Animation|Children', 2);
insert into movie (title, genre, review) values (29, 'Bedknobs and Broomsticks', 'Adventure|Children|Musical', 4);
insert into movie (title, genre, review) values (30, 'Zero Degrees of Separation', 'Documentary', 2);
insert into movie (title, genre, review) values (31, 'San Francisco', 'Drama|Musical|Romance', 1);
insert into movie (title, genre, review) values (32, '3 Blind Mice', 'Crime|Mystery|Romance|Thriller', 3);
insert into movie (title, genre, review) values (33, 'War Is Over, The (Guerre est finie, La)', 'Drama', 2);
insert into movie (title, genre, review) values (34, 'Music for One Apartment and Six Drummers', 'Comedy', 4);
insert into movie (title, genre, review) values (35, 'Awakening, The', 'Horror|Thriller', 1);
insert into movie (title, genre, review) values (36, 'Rat Savior, The (Izbavitelj)', 'Horror|Sci-Fi', 1);
insert into movie (title, genre, review) values (37, 'I''ll Be There', 'Comedy|Musical|Romance', 3);
insert into movie (title, genre, review) values (38, 'Mechanic, The', 'Action|Thriller', 3);
insert into movie (title, genre, review) values (39, 'Beasts of the Southern Wild', 'Drama|Fantasy', 1);
insert into movie (title, genre, review) values (40, 'Bombshell', 'Comedy|Drama|Romance', 2);
insert into movie (title, genre, review) values (41, 'My Name Is Bruce', 'Comedy|Horror', 2);
insert into movie (title, genre, review) values (42, 'Picnic at Hanging Rock', 'Drama|Mystery', 2);
insert into movie (title, genre, review) values (43, 'Jaws 2', 'Horror|Thriller', 1);
insert into movie (title, genre, review) values (44, 'Song of the South', 'Adventure|Animation|Children|Musical', 1);
insert into movie (title, genre, review) values (45, 'Deceivers, The', 'Adventure|Drama|Thriller', 5);
insert into movie (title, genre, review) values (46, 'Body Snatchers', 'Horror|Sci-Fi|Thriller', 1);
insert into movie (title, genre, review) values (47, 'Titanic', 'Action|Drama|Romance', 4);
insert into movie (title, genre, review) values (48, 'I Always Wanted to Be a Gangster (J''ai toujours rêvé d''être un gangster)', 'Comedy|Crime|Drama', 1);
insert into movie (title, genre, review) values (49, 'Cimarron', 'Drama|Western', 1);
insert into movie (title, genre, review) values (50, 'Short Circuit', 'Comedy|Sci-Fi', 5);
insert into movie (title, genre, review) values (51, 'Keane', 'Mystery|Thriller', 3);
insert into movie (title, genre, review) values (52, 'Love Trap, The', 'Comedy|Romance', 2);
insert into movie (title, genre, review) values (53, 'Last of the Unjust, The (Dernier des injustes, Le)', 'Documentary', 1);
insert into movie (title, genre, review) values (54, 'Trailer Park of Terror', 'Horror|Thriller', 5);
insert into movie (title, genre, review) values (55, 'Common Places (a.k.a. Common Ground) (Lugares comunes)', 'Drama', 4);
insert into movie (title, genre, review) values (56, 'Den enskilde medborgaren', 'Comedy', 5);
insert into movie (title, genre, review) values (57, 'Hitch', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values (58, 'Red Scorpion', 'Action', 2);
insert into movie (title, genre, review) values (59, 'Ghostbusters (a.k.a. Ghost Busters)', 'Action|Comedy|Sci-Fi', 4);
insert into movie (title, genre, review) values (60, 'Dragonlance: Dragons of Autumn Twilight', 'Action|Adventure|Animation|Fantasy', 2);
insert into movie (title, genre, review) values (61, 'Hero: Love Story of a Spy, The', 'Action|Adventure|Drama|Musical|Romance|Thriller|War', 1);
insert into movie (title, genre, review) values (62, 'Tyler Perry''s Madea''s Witness Protection', 'Comedy', 4);
insert into movie (title, genre, review) values (63, 'Kwik Stop', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values (64, 'H.M. Pulham, Esq.', 'Drama|Romance', 2);
insert into movie (title, genre, review) values (65, 'Fugitive, The', 'Thriller', 5);
insert into movie (title, genre, review) values (66, 'Italian Job, The', 'Action|Comedy|Crime', 2);
insert into movie (title, genre, review) values (67, 'Leprechaun', 'Comedy|Horror', 3);
insert into movie (title, genre, review) values (68, 'My Mother''s Courage (Mutters Courage)', 'Comedy', 2);
insert into movie (title, genre, review) values (69, 'Blue Max, The', 'Adventure|Drama|War', 2);
insert into movie (title, genre, review) values (70, 'Taboo (Gohatto)', 'Drama', 1);
insert into movie (title, genre, review) values (71, 'Thirst (Bakjwi)', 'Drama|Horror', 2);
insert into movie (title, genre, review) values (72, 'Pick-up Artist, The', 'Comedy|Romance', 2);
insert into movie (title, genre, review) values (73, 'Vernon, Florida', 'Documentary', 3);
insert into movie (title, genre, review) values (74, 'Freedom', 'Drama', 5);
insert into movie (title, genre, review) values (75, 'Safe Passage', 'Drama', 2);
insert into movie (title, genre, review) values (76, 'Twilight Saga: Eclipse, The', 'Fantasy|Romance|Thriller|IMAX', 3);
insert into movie (title, genre, review) values (77, 'Good Old Fashioned Orgy, A', 'Comedy', 4);
insert into movie (title, genre, review) values (78, 'Takedown: The DNA of GSP', 'Documentary', 4);
insert into movie (title, genre, review) values (79, 'Sofia''s Last Ambulance (Poslednaka lineika na Sofia)', 'Documentary', 2);
insert into movie (title, genre, review) values (80, 'Unfinished Sky', 'Drama|Romance', 5);
insert into movie (title, genre, review) values (81, 'Not as a Stranger', 'Drama', 3);
insert into movie (title, genre, review) values (82, 'Brave Little Toaster, The', 'Animation|Children', 1);
insert into movie (title, genre, review) values (83, 'Whatever Lola Wants', 'Drama', 4);
insert into movie (title, genre, review) values (84, 'Not Another Teen Movie', 'Comedy', 3);
insert into movie (title, genre, review) values (85, 'Kai Po Che!', 'Drama', 5);
insert into movie (title, genre, review) values (86, 'School Daze', 'Drama', 2);
insert into movie (title, genre, review) values (87, 'Raja', 'Drama', 2);
insert into movie (title, genre, review) values (88, 'External Affairs', 'Drama', 5);
insert into movie (title, genre, review) values (89, 'Barbarosa', 'Western', 3);
insert into movie (title, genre, review) values (90, 'Race', 'Action|Comedy', 1);
insert into movie (title, genre, review) values (91, 'Parent Trap, The', 'Children|Comedy|Romance', 4);
insert into movie (title, genre, review) values (92, 'Root of All Evil?', 'Documentary', 3);
insert into movie (title, genre, review) values (93, 'Beck - Familjen', 'Crime|Mystery|Thriller', 5);
insert into movie (title, genre, review) values (94, 'Wicked', 'Thriller', 3);
insert into movie (title, genre, review) values (95, 'Keeping the Faith', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values (96, 'Around the World in 80 Days', 'Adventure|Comedy', 3);
insert into movie (title, genre, review) values (97, 'Elvis: That''s the Way It Is', 'Documentary', 2);
insert into movie (title, genre, review) values (98, 'Child of God', 'Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values (99, 'Delivery, The', 'Action|Adventure|Horror|Thriller', 4);
insert into movie (title, genre, review) values (100, 'I''m Not There', 'Drama', 2);
insert into movie (title, genre, review) values (101, 'Jack Frost', 'Comedy|Fantasy|Horror', 4);
insert into movie (title, genre, review) values (102, 'Advance to the Rear', 'Comedy|War|Western', 3);
insert into movie (title, genre, review) values (103, 'Someone Like You (Unnaipol Oruvan)', 'Crime|Drama', 2);
insert into movie (title, genre, review) values (104, 'Making Love', 'Drama', 5);
insert into movie (title, genre, review) values (105, 'Pleasantville', 'Comedy|Drama|Fantasy', 2);
insert into movie (title, genre, review) values (106, 'I Killed My Mother (J''ai tué ma mère)', 'Drama', 5);
insert into movie (title, genre, review) values (107, 'Alvin and the Chipmunks: The Squeakquel', 'Animation|Children|Comedy|Musical', 5);
insert into movie (title, genre, review) values (108, 'Great Communist Bank Robbery (Marele jaf comunist)', 'Documentary', 2);
insert into movie (title, genre, review) values (109, 'Gallowwalkers', 'Action|Horror|Sci-Fi|Western', 5);
insert into movie (title, genre, review) values (110, 'Pandora''s Box (Pandora''nin kutusu)', 'Drama', 5);
insert into movie (title, genre, review) values (111, 'Rushmore', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values (112, 'Grizzly Man', 'Documentary', 1);
insert into movie (title, genre, review) values (113, 'The Beales of Grey Gardens', 'Documentary', 4);
insert into movie (title, genre, review) values (114, 'Poetic Justice', 'Drama', 2);
insert into movie (title, genre, review) values (115, 'Paranormal Activity 4', 'Horror|IMAX', 5);
insert into movie (title, genre, review) values (116, 'Fear', 'Thriller', 4);
insert into movie (title, genre, review) values (117, 'Bride Comes Home, The', 'Comedy|Romance', 2);
insert into movie (title, genre, review) values (118, 'Threesome', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values (119, 'Billy Elliot', 'Drama', 3);
insert into movie (title, genre, review) values (120, 'Lilith', 'Drama', 2);
insert into movie (title, genre, review) values (121, 'Steel', 'Action', 5);
insert into movie (title, genre, review) values (122, 'Mutantes', 'Documentary', 4);
insert into movie (title, genre, review) values (123, 'Paradise: Hope (Paradies: Hoffnung)', 'Drama', 4);
insert into movie (title, genre, review) values (124, 'Nice Guys Sleep Alone', 'Comedy|Romance', 2);
insert into movie (title, genre, review) values (125, 'CBGB', 'Drama', 2);
insert into movie (title, genre, review) values (126, 'A Walk in the Old City of Warsaw', 'Documentary', 2);
insert into movie (title, genre, review) values (127, 'Tucker: The Man and His Dream', 'Drama', 3);
insert into movie (title, genre, review) values (128, 'Mary and Martha', 'Drama', 1);
insert into movie (title, genre, review) values (129, 'Reagan', 'Documentary', 2);
insert into movie (title, genre, review) values (130, 'Black Dog', 'Action|Thriller', 5);
insert into movie (title, genre, review) values (131, 'Cougars, Inc.', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values (132, 'Tenderness (Hellyys)', 'Comedy', 1);
insert into movie (title, genre, review) values (133, 'Marius', 'Comedy|Drama|Romance', 3);
insert into movie (title, genre, review) values (134, 'The Damned', 'Horror|Mystery|Thriller', 5);
insert into movie (title, genre, review) values (135, 'Catacombs', 'Horror|Thriller', 2);
insert into movie (title, genre, review) values (136, 'Swept Away', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values (137, 'Prometheus', 'Action|Horror|Sci-Fi|IMAX', 2);
insert into movie (title, genre, review) values (138, 'Dragon Ball Z: The Return of Cooler (Doragon bôru Z 6: Gekitotsu! Hyakuoku pawâ no senshi)', 'Action|Adventure|Animation', 1);
insert into movie (title, genre, review) values (139, 'Paranoia Agent', 'Animation|Crime|Drama|Horror|Mystery', 4);
insert into movie (title, genre, review) values (140, 'Father Hood', 'Comedy', 2);
insert into movie (title, genre, review) values (141, 'Friend Is a Treasure, A (Chi Trova Un Amico, Trova un Tesoro) (Who Finds a Friend Finds a Treasure)', 'Action|Adventure|Comedy', 4);
insert into movie (title, genre, review) values (142, 'Howling IV: The Original Nightmare', 'Horror', 2);
insert into movie (title, genre, review) values (143, 'Landet som icke är', 'Drama', 2);
insert into movie (title, genre, review) values (144, 'Born to Be Wild', 'Documentary|IMAX', 5);
insert into movie (title, genre, review) values (145, 'Make Them Die Slowly (Cannibal Ferox)', 'Horror', 5);
insert into movie (title, genre, review) values (146, 'Closer You Get, The', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values (147, 'Calle 54', 'Documentary|Musical', 1);
insert into movie (title, genre, review) values (148, 'Good German, The', 'Drama|Mystery|Thriller', 2);
insert into movie (title, genre, review) values (149, 'Kill Me Later', 'Romance|Thriller', 5);
insert into movie (title, genre, review) values (150, 'Zincirbozan', 'Crime|Drama', 2);
insert into movie (title, genre, review) values (151, 'Children, The', 'Horror', 2);
insert into movie (title, genre, review) values (152, 'From Hell It Came', 'Horror', 5);
insert into movie (title, genre, review) values (153, 'Black Friday', 'Crime|Drama|Horror|Sci-Fi', 4);
insert into movie (title, genre, review) values (154, 'Mrs. Brown''s Boys D''Movie', 'Comedy', 3);
insert into movie (title, genre, review) values (155, 'No Distance Left to Run', 'Documentary', 2);
insert into movie (title, genre, review) values (156, 'H6: Diario de un asesino', 'Horror|Thriller', 3);
insert into movie (title, genre, review) values (157, 'Dr. Goldfoot and the Bikini Machine', 'Comedy', 2);
insert into movie (title, genre, review) values (158, 'Made for Each Other', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values (159, 'Snow Queen', 'Animation|Fantasy', 5);
insert into movie (title, genre, review) values (160, 'Goodbye Girl, The', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values (161, 'Xanadu', 'Fantasy|Musical|Romance', 5);
insert into movie (title, genre, review) values (162, 'Drifting Clouds (Kauas pilvet karkaavat)', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values (163, '112 Weddings', 'Documentary|Romance', 2);
insert into movie (title, genre, review) values (164, 'In China They Eat Dogs (I Kina spiser de hunde)', 'Action|Comedy', 2);
insert into movie (title, genre, review) values (165, 'Robe, The', 'Drama', 5);
insert into movie (title, genre, review) values (166, 'I Live My Life', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values (167, 'Amadeus', 'Drama', 1);
insert into movie (title, genre, review) values (168, 'Chiedimi se sono felice', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values (169, 'Truth About Charlie, The', 'Mystery|Thriller', 4);
insert into movie (title, genre, review) values (170, 'Olympia Part One: Festival of the Nations (Olympia 1. Teil - Fest der Völker)', 'Documentary', 5);
insert into movie (title, genre, review) values (171, 'Pushover', 'Crime|Drama|Film-Noir', 3);
insert into movie (title, genre, review) values (172, 'Electile Dysfunction', 'Documentary', 1);
insert into movie (title, genre, review) values (173, 'Human Resources Manager, The', 'Drama', 2);
insert into movie (title, genre, review) values (174, 'The Rag Man', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (175, 'Upside Down: The Creation Records Story', 'Documentary', 2);
insert into movie (title, genre, review) values (176, 'Bless the Child', 'Thriller', 4);
insert into movie (title, genre, review) values (177, 'Maid of Salem', 'Drama', 5);
insert into movie (title, genre, review) values (178, 'Visitors, The', 'Crime|Drama|Thriller', 2);
insert into movie (title, genre, review) values (179, 'Flesh for Frankenstein (a.k.a. Andy Warhol''s Frankenstein)', 'Drama|Horror|Sci-Fi', 5);
insert into movie (title, genre, review) values (180, 'Paris, I Love You (Paris, je t''aime)', 'Romance', 1);
insert into movie (title, genre, review) values (181, 'Mercy ', 'Horror|Thriller', 2);
insert into movie (title, genre, review) values (182, 'Cold Trail (Köld slóð)', 'Drama|Mystery|Thriller', 2);
insert into movie (title, genre, review) values (183, 'Deadbolt', 'Thriller', 4);
insert into movie (title, genre, review) values (184, 'David and Lisa', 'Drama', 5);
insert into movie (title, genre, review) values (185, 'Scandali nudi', '(no genres listed)', 4);
insert into movie (title, genre, review) values (186, 'Son of Babylon (Syn Babilonu)', 'Drama', 1);
insert into movie (title, genre, review) values (187, 'Teenage Paparazzo', 'Documentary', 2);
insert into movie (title, genre, review) values (188, 'Avenging Conscience, The', 'Drama|Horror', 1);
insert into movie (title, genre, review) values (189, 'Foolish Wives', 'Drama', 2);
insert into movie (title, genre, review) values (190, 'Tobor the Great', 'Children|Sci-Fi', 5);
insert into movie (title, genre, review) values (191, 'Green Ray, The (Rayon vert, Le)', 'Drama|Romance', 2);
insert into movie (title, genre, review) values (192, 'How to Kill Your Neighbor''s Dog', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values (193, 'Speed & Angels', 'Documentary|Drama', 1);
insert into movie (title, genre, review) values (194, 'Goldfinger', 'Action|Adventure|Thriller', 1);
insert into movie (title, genre, review) values (195, 'What No One Knows (Det som ingen ved)', 'Drama|Thriller', 4);
insert into movie (title, genre, review) values (196, 'Brink''s Job, The', 'Comedy|Crime|Drama', 5);
insert into movie (title, genre, review) values (197, 'Lassie', 'Adventure|Children', 5);
insert into movie (title, genre, review) values (198, 'Accidental Golfer, The (Den ofrivillige golfaren)', 'Comedy', 3);
insert into movie (title, genre, review) values (199, 'Ingrid', 'Drama', 3);
insert into movie (title, genre, review) values (200, 'Being Flynn', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (201, 'Pink Floyd: The Wall', 'Drama|Musical', 1);
insert into movie (title, genre, review) values (202, 'Resident Evil: Apocalypse', 'Action|Horror|Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values (203, 'Gantz: Perfect Answer', 'Action|Mystery|Sci-Fi', 4);
insert into movie (title, genre, review) values (204, 'Demonic', 'Horror|Thriller', 1);
insert into movie (title, genre, review) values (205, 'New York Lightboard Record', 'Animation|Documentary', 5);
insert into movie (title, genre, review) values (206, 'Acid House, The', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (207, 'Sextette', 'Comedy|Musical|Romance', 4);
insert into movie (title, genre, review) values (208, 'Brigham City', 'Crime|Drama|Mystery', 1);
insert into movie (title, genre, review) values (209, 'Gimme the Loot', 'Drama', 5);
insert into movie (title, genre, review) values (210, 'Circle of Eight', 'Horror|Mystery', 1);
insert into movie (title, genre, review) values (211, 'The Biggest Bundle of Them All', 'Comedy|Crime', 4);
insert into movie (title, genre, review) values (212, 'Mildred Pierce', 'Drama|Film-Noir', 4);
insert into movie (title, genre, review) values (213, 'Hound of the Baskervilles, The', 'Crime|Horror|Mystery', 1);
insert into movie (title, genre, review) values (214, 'Just Anybody (Le premier venu)', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (215, 'Lost Horizon', 'Adventure|Drama|Fantasy|Musical|Romance', 2);
insert into movie (title, genre, review) values (216, 'Scarlet and the Black, The', 'Action|Drama|War', 2);
insert into movie (title, genre, review) values (217, 'Transylvania 6-5000', 'Comedy|Horror', 4);
insert into movie (title, genre, review) values (218, 'Rejs', 'Comedy', 4);
insert into movie (title, genre, review) values (219, 'Paint It Yellow (Rang De Basanti)', 'Action|Comedy|Drama', 2);
insert into movie (title, genre, review) values (220, 'The Little Fox', 'Adventure|Animation|Children', 5);
insert into movie (title, genre, review) values (221, 'That Darn Cat', 'Children|Comedy|Mystery', 1);
insert into movie (title, genre, review) values (222, 'Trauma', 'Horror|Mystery|Thriller', 3);
insert into movie (title, genre, review) values (223, 'Mark of the Devil (Hexen bis aufs Blut gequält)', 'Drama|Horror', 1);
insert into movie (title, genre, review) values (224, 'Forrest Gump', 'Comedy|Drama|Romance|War', 3);
insert into movie (title, genre, review) values (225, 'Courier', 'Comedy|Drama|Romance', 3);
insert into movie (title, genre, review) values (226, 'Murder by Proxy: How America Went Postal', 'Documentary', 2);
insert into movie (title, genre, review) values (227, 'Estomago: A Gastronomic Story', 'Drama', 1);
insert into movie (title, genre, review) values (228, 'Whitecoats', 'Comedy', 1);
insert into movie (title, genre, review) values (229, 'Flypaper', 'Comedy|Crime', 1);
insert into movie (title, genre, review) values (230, 'No', 'Drama', 4);
insert into movie (title, genre, review) values (231, 'Alexandria... Why? (Iskanderija... lih?)', 'Drama', 3);
insert into movie (title, genre, review) values (232, 'Reclaim Your Brain (Free Rainer)', 'Comedy|Crime|Drama|Romance', 2);
insert into movie (title, genre, review) values (233, 'Valentine', 'Horror|Mystery', 3);
insert into movie (title, genre, review) values (234, 'Paying the Price: Killing the Children of Iraq', 'Documentary', 2);
insert into movie (title, genre, review) values (235, 'New World, The', 'Adventure|Drama|Romance', 2);
insert into movie (title, genre, review) values (236, 'Everybody Wins', 'Drama|Mystery|Thriller', 4);
insert into movie (title, genre, review) values (237, 'Beloved', 'Drama', 4);
insert into movie (title, genre, review) values (238, 'Lucky Lady', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values (239, 'Broken', 'Drama', 3);
insert into movie (title, genre, review) values (240, 'Stella Street', 'Comedy', 2);
insert into movie (title, genre, review) values (241, 'Tales of Ordinary Madness (Storie di Ordinaria Follia)', 'Drama', 2);
insert into movie (title, genre, review) values (242, 'Empire', 'Crime|Drama', 1);
insert into movie (title, genre, review) values (243, 'Kill Bill: Vol. 2', 'Action|Drama|Thriller', 2);
insert into movie (title, genre, review) values (244, 'Black White + Gray: A Portrait of Sam Wagstaff and Robert Mapplethorpe ', 'Documentary', 4);
insert into movie (title, genre, review) values (245, 'Staying Together', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (246, 'Very Social Secretary, A', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values (247, 'Squid and the Whale, The', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (248, 'Playing ''In the Company of Men'' (En jouant ''Dans la compagnie des hommes'')', 'Drama', 5);
insert into movie (title, genre, review) values (249, 'Forever Hardcore: The Documentary', 'Documentary', 4);
insert into movie (title, genre, review) values (250, 'Casanova', 'Comedy|Drama|Romance', 1);
insert into movie (title, genre, review) values (251, 'Fitzcarraldo', 'Adventure|Drama', 4);
insert into movie (title, genre, review) values (252, 'Last Wave, The', 'Fantasy|Mystery|Thriller', 4);
insert into movie (title, genre, review) values (253, 'Happy Accidents', 'Romance|Sci-Fi', 1);
insert into movie (title, genre, review) values (254, 'Goodbye, Columbus', 'Comedy|Drama|Romance', 1);
insert into movie (title, genre, review) values (255, 'The Hire: Beat the Devil', 'Action|Adventure|Comedy', 3);
insert into movie (title, genre, review) values (256, 'Boy Who Could Fly, The', 'Drama|Fantasy', 2);
insert into movie (title, genre, review) values (257, 'Lemora: A Child''s Tale of the Supernatural', 'Horror', 5);
insert into movie (title, genre, review) values (258, 'Wirey Spindell', 'Comedy', 5);
insert into movie (title, genre, review) values (259, 'Cocktail', 'Drama|Romance', 4);
insert into movie (title, genre, review) values (260, 'Once Upon a Time (Der var engang)', 'Romance', 4);
insert into movie (title, genre, review) values (261, 'Atomic Twister', 'Action|Drama|Sci-Fi', 2);
insert into movie (title, genre, review) values (262, 'Year Zero: The Silent Death of Cambodia', 'Documentary', 4);
insert into movie (title, genre, review) values (263, 'Islands in the Stream', 'Drama', 3);
insert into movie (title, genre, review) values (264, 'Spirit: Stallion of the Cimarron', 'Adventure|Animation|Children|Western', 4);
insert into movie (title, genre, review) values (265, 'Very Happy Alexander (Alexandre le bienheureux)', 'Comedy|Romance', 3);
insert into movie (title, genre, review) values (266, 'East-West (Est-ouest)', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (267, 'Big Bad Mama', 'Action|Comedy', 1);
insert into movie (title, genre, review) values (268, 'On the Waterfront', 'Crime|Drama', 3);
insert into movie (title, genre, review) values (269, 'Mo', 'Horror', 4);
insert into movie (title, genre, review) values (270, 'Vizontele Tuuba', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values (271, 'Konopielka', 'Comedy', 4);
insert into movie (title, genre, review) values (272, '3 Backyards', 'Drama', 3);
insert into movie (title, genre, review) values (273, 'Piece of the Action, A', 'Crime|Drama', 2);
insert into movie (title, genre, review) values (274, 'Two Mules for Sister Sara', 'Comedy|War|Western', 3);
insert into movie (title, genre, review) values (275, 'Road, The', 'Crime|Drama|Horror|Thriller', 3);
insert into movie (title, genre, review) values (276, 'Capture of Bigfoot, The', 'Adventure|Horror|Sci-Fi', 4);
insert into movie (title, genre, review) values (277, 'The Police Serve the Citizens?', 'Action|Crime', 1);
insert into movie (title, genre, review) values (278, 'Bucket of Blood, A (Dark Secrets) (Death Artist, The)', 'Comedy|Horror|Thriller', 2);
insert into movie (title, genre, review) values (279, 'Hovering Over the Water (À Flor do Mar)', 'Drama|Romance', 4);
insert into movie (title, genre, review) values (280, 'Boy with Green Hair, The', 'Children|Drama', 3);
insert into movie (title, genre, review) values (281, 'Tukkijoella', 'Drama', 3);
insert into movie (title, genre, review) values (282, 'Big Tease, The', 'Comedy', 3);
insert into movie (title, genre, review) values (283, 'Black Robe', 'Adventure|Drama', 4);
insert into movie (title, genre, review) values (284, 'Blackout', 'Action|Thriller', 3);
insert into movie (title, genre, review) values (285, 'Bells from the Deep', 'Documentary', 4);
insert into movie (title, genre, review) values (286, 'Flash of Genius', 'Drama', 4);
insert into movie (title, genre, review) values (287, 'At Long Last Love', 'Comedy|Musical|Romance', 1);
insert into movie (title, genre, review) values (288, 'Rebecca', 'Drama|Mystery|Romance|Thriller', 1);
insert into movie (title, genre, review) values (289, 'Crazy as Hell', 'Drama', 3);
insert into movie (title, genre, review) values (290, 'African Queen, The', 'Adventure|Comedy|Romance|War', 2);
insert into movie (title, genre, review) values (291, 'Cookout, The', 'Comedy', 4);
insert into movie (title, genre, review) values (292, 'If You Are the One', 'Comedy|Romance', 3);
insert into movie (title, genre, review) values (293, 'Nina Frisk', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values (294, 'Inherit the Wind', 'Drama', 4);
insert into movie (title, genre, review) values (295, 'Horseman, The', 'Crime|Thriller', 4);
insert into movie (title, genre, review) values (296, 'Tora-san Our Lovable Tramp (Otoko wa tsurai yo)', 'Comedy|Drama|Romance', 1);
insert into movie (title, genre, review) values (297, 'Aftermath: Population Zero', 'Documentary|Sci-Fi', 2);
insert into movie (title, genre, review) values (298, 'Amour', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (299, 'Substance of Fire, The', 'Drama', 3);
insert into movie (title, genre, review) values (300, 'Clock, The', 'Adventure|Drama|Romance', 4);
insert into movie (title, genre, review) values (301, 'A Via Láctea', 'Drama', 2);
insert into movie (title, genre, review) values (302, 'Herod''s Law (Ley de Herodes, La)', 'Comedy|Crime|Mystery', 3);
insert into movie (title, genre, review) values (303, 'New York Minute', 'Action|Adventure|Comedy', 5);
insert into movie (title, genre, review) values (304, 'Hearts Divided', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (305, 'Flying Scotsman, The', 'Drama', 4);
insert into movie (title, genre, review) values (306, 'Saving God', 'Crime|Drama', 5);
insert into movie (title, genre, review) values (307, 'The Hound of the Baskervilles', 'Adventure|Drama|Horror|Mystery', 1);
insert into movie (title, genre, review) values (308, 'Melancholia', 'Drama|Sci-Fi', 2);
insert into movie (title, genre, review) values (309, 'Blue Spring (Aoi haru)', 'Drama', 3);
insert into movie (title, genre, review) values (310, 'Bambi 2', 'Animation|Children|Drama', 2);
insert into movie (title, genre, review) values (311, 'Mike''s New Car', 'Animation|Comedy', 3);
insert into movie (title, genre, review) values (312, 'Cameraman''s Revenge, The (Mest kinematograficheskogo operatora)', 'Animation|Comedy', 5);
insert into movie (title, genre, review) values (313, 'City of Your Final Destination, The', 'Drama', 4);
insert into movie (title, genre, review) values (314, 'Half Past Dead', 'Action|Crime|Thriller', 5);
insert into movie (title, genre, review) values (315, 'Girl by the Lake, The (La ragazza del lago)', 'Drama|Mystery|Thriller', 4);
insert into movie (title, genre, review) values (316, 'Star Trek IV: The Voyage Home', 'Adventure|Comedy|Sci-Fi', 2);
insert into movie (title, genre, review) values (317, 'Princess of Montpensier, The (La princesse de Montpensier)', 'Action|Drama|Romance', 3);
insert into movie (title, genre, review) values (318, 'Street with No Name, The', 'Crime|Drama|Film-Noir|Thriller', 1);
insert into movie (title, genre, review) values (319, 'American Soldier, The (Der amerikanische Soldat)', 'Drama', 4);
insert into movie (title, genre, review) values (320, 'Benji ', 'Documentary', 2);
insert into movie (title, genre, review) values (321, 'Suture', 'Film-Noir|Thriller', 2);
insert into movie (title, genre, review) values (322, 'Treasure of the Sierra Madre, The', 'Action|Adventure|Drama|Western', 3);
insert into movie (title, genre, review) values (323, 'Girl, Interrupted', 'Drama', 2);
insert into movie (title, genre, review) values (324, 'West Point Story, The', 'Comedy|Musical', 1);
insert into movie (title, genre, review) values (325, 'My Ain Folk', 'Drama', 2);
insert into movie (title, genre, review) values (326, 'Conspiracy of Torture, The (Beatrice Cenci)', 'Drama', 4);
insert into movie (title, genre, review) values (327, 'Naughty Room, The', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (328, 'Jean Gentil', 'Drama', 3);
insert into movie (title, genre, review) values (329, 'Gentlemen', 'Drama|Romance|Thriller', 2);
insert into movie (title, genre, review) values (330, 'Giant Claw, The', 'Horror|Sci-Fi', 5);
insert into movie (title, genre, review) values (331, 'Vinyan', 'Drama|Horror|Thriller', 3);
insert into movie (title, genre, review) values (332, 'Armstrong Lie, The', 'Documentary', 1);
insert into movie (title, genre, review) values (333, 'A Phantasy', 'Animation', 2);
insert into movie (title, genre, review) values (334, 'You Only Live Twice', 'Action|Adventure|Sci-Fi|Thriller', 2);
insert into movie (title, genre, review) values (335, 'Dragonwyck', 'Drama|Mystery|Thriller', 5);
insert into movie (title, genre, review) values (336, '''Neath the Arizona Skies', 'Western', 4);
insert into movie (title, genre, review) values (337, 'Losin'' It', 'Comedy', 4);
insert into movie (title, genre, review) values (338, 'Alone in the Dark', 'Horror', 2);
insert into movie (title, genre, review) values (339, 'Time Bandits', 'Adventure|Comedy|Fantasy|Sci-Fi', 4);
insert into movie (title, genre, review) values (340, 'Painted Lady', 'Crime|Drama|Thriller', 4);
insert into movie (title, genre, review) values (341, 'December 7th', 'Documentary|War', 3);
insert into movie (title, genre, review) values (342, 'Hoax, The', 'Crime|Drama', 4);
insert into movie (title, genre, review) values (343, 'The Man They Could Not Hang', 'Crime|Horror|Sci-Fi', 1);
insert into movie (title, genre, review) values (344, 'Enquiring Minds: The Untold Story of the Man Behind the National Enquirer', 'Documentary', 4);
insert into movie (title, genre, review) values (345, 'Once in the Life', 'Crime|Drama', 2);
insert into movie (title, genre, review) values (346, 'Death Note 2: The Last Name', 'Adventure|Crime|Drama', 1);
insert into movie (title, genre, review) values (347, 'Atlantis: The Lost Empire', 'Adventure|Animation|Children|Fantasy', 5);
insert into movie (title, genre, review) values (348, 'Battlestar Galactica: Razor', 'Action|Drama|Sci-Fi|Thriller', 2);
insert into movie (title, genre, review) values (349, 'Cement Garden, The', 'Drama', 4);
insert into movie (title, genre, review) values (350, 'Starcrash (a.k.a. Star Crash)', 'Action|Adventure|Fantasy|Sci-Fi', 5);
insert into movie (title, genre, review) values (351, 'Rough Night in Jericho', 'Western', 3);
insert into movie (title, genre, review) values (352, 'Pont du Nord, Le', 'Comedy|Fantasy|Mystery', 4);
insert into movie (title, genre, review) values (353, 'Great!', 'Comedy', 1);
insert into movie (title, genre, review) values (354, 'Life Is a Long Quiet River (La vie est un long fleuve tranquille)', 'Comedy', 4);
insert into movie (title, genre, review) values (355, 'Beware of a Holy Whore (Warnung vor einer heiligen Nutte)', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values (356, 'Garden State', 'Comedy|Drama|Romance', 1);
insert into movie (title, genre, review) values (357, 'IMAX: Coral Reef Adventure', 'Children|Documentary|IMAX', 4);
insert into movie (title, genre, review) values (358, 'Battle Royale (Batoru rowaiaru)', 'Action|Drama|Horror|Thriller', 5);
insert into movie (title, genre, review) values (359, 'Putney Swope', 'Comedy', 3);
insert into movie (title, genre, review) values (360, 'Strike (Stachka)', 'Drama', 2);
insert into movie (title, genre, review) values (361, 'Horseman, The', 'Crime|Thriller', 2);
insert into movie (title, genre, review) values (362, 'Belle', 'Drama', 2);
insert into movie (title, genre, review) values (363, 'Notting Hill', 'Comedy|Romance', 2);
insert into movie (title, genre, review) values (364, 'Ruggles of Red Gap', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values (365, 'Recipe for Love', 'Romance', 4);
insert into movie (title, genre, review) values (366, 'Kill List', 'Horror|Mystery|Thriller', 5);
insert into movie (title, genre, review) values (367, 'Beast Within, The', 'Horror', 4);
insert into movie (title, genre, review) values (368, 'House of the Spirits, The', 'Drama|Romance', 5);
insert into movie (title, genre, review) values (369, 'Crossfire Hurricane', 'Documentary|Musical', 5);
insert into movie (title, genre, review) values (370, 'Sudden Impact', 'Crime|Thriller', 5);
insert into movie (title, genre, review) values (371, 'Harmonists, The', 'Drama', 3);
insert into movie (title, genre, review) values (372, 'Medallion, The', 'Action|Comedy|Crime|Fantasy', 4);
insert into movie (title, genre, review) values (373, 'Who the F**K Is Arthur Fogel', 'Documentary', 2);
insert into movie (title, genre, review) values (374, 'Slim Susie (Smala Sussie)', 'Comedy|Crime|Mystery', 5);
insert into movie (title, genre, review) values (375, 'Money (L''argent)', 'Crime|Drama', 4);
insert into movie (title, genre, review) values (376, 'Trouble with Girls, The', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values (377, 'Narrien illat ', 'Comedy|Drama|Musical', 5);
insert into movie (title, genre, review) values (378, 'Melancholia', 'Drama|Sci-Fi', 2);
insert into movie (title, genre, review) values (379, 'Idiot''s Delight', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values (380, 'Happy, Texas', 'Comedy', 2);
insert into movie (title, genre, review) values (381, 'Kind Lady', 'Drama|Thriller', 5);
insert into movie (title, genre, review) values (382, 'Chisum', 'Western', 1);
insert into movie (title, genre, review) values (383, 'Just Friends?', 'Romance', 4);
insert into movie (title, genre, review) values (384, 'No Mercy', 'Action|Crime|Thriller', 2);
insert into movie (title, genre, review) values (385, 'Attack of the Crab Monsters', 'Horror|Sci-Fi', 1);
insert into movie (title, genre, review) values (386, 'Lone Ranger, The', 'Action|Adventure|Western|IMAX', 2);
insert into movie (title, genre, review) values (387, 'Lucky You', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values (388, 'New Year''s Eve', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values (389, 'Act of Violence', 'Drama|Film-Noir|Thriller', 3);
insert into movie (title, genre, review) values (390, 'Abbott and Costello Meet Dr. Jekyll and Mr. Hyde', 'Comedy|Horror|Sci-Fi', 5);
insert into movie (title, genre, review) values (391, 'Vizontele', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values (392, 'Over the Hedge', 'Adventure|Animation|Children|Comedy', 2);
insert into movie (title, genre, review) values (393, 'Eat', 'Documentary', 2);
insert into movie (title, genre, review) values (394, 'Chimes at Midnight (Campanadas a medianoche)', 'Comedy|Drama|War', 3);
insert into movie (title, genre, review) values (395, 'Day, The', 'Drama|Sci-Fi|Thriller', 2);
insert into movie (title, genre, review) values (396, 'Bronx Obama', 'Documentary', 5);
insert into movie (title, genre, review) values (397, 'I Saw the Devil (Akmareul boatda)', 'Crime|Thriller', 2);
insert into movie (title, genre, review) values (398, 'Last Night', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (399, 'Brighter Summer Day, A (Gu ling jie shao nian sha ren shi jian)', 'Drama|Romance', 5);
insert into movie (title, genre, review) values (400, 'Rise & Fall of ECW, The', 'Documentary', 3);
insert into movie (title, genre, review) values (401, 'MacGyver: Lost Treasure of Atlantis', 'Action|Adventure', 1);
insert into movie (title, genre, review) values (402, 'Luminarias', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values (403, 'Don''t Look Back (Ne te retourne pas)', 'Drama|Horror|Mystery|Thriller', 1);
insert into movie (title, genre, review) values (404, 'Garden Lovers (Eedenistä pohjoiseen)', 'Documentary', 2);
insert into movie (title, genre, review) values (405, 'Love Affair', 'Drama|Romance', 5);
insert into movie (title, genre, review) values (406, 'Division III: Football''s Finest', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values (407, 'Chronicle of an Escape (Crónica de una fuga)', 'Thriller', 3);
insert into movie (title, genre, review) values (408, 'The Unexpected Love', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values (409, 'Middle of the World, The (O Caminho das Nuvens)', 'Drama', 4);
insert into movie (title, genre, review) values (410, 'As Above, So Below', 'Horror|Thriller', 2);
insert into movie (title, genre, review) values (411, 'Flightplan', 'Action|Drama|Thriller', 4);
insert into movie (title, genre, review) values (412, 'Dredd', 'Action|Sci-Fi', 4);
insert into movie (title, genre, review) values (413, 'Africa addio', 'Documentary', 1);
insert into movie (title, genre, review) values (414, 'Boy Meets Girl', 'Drama', 2);
insert into movie (title, genre, review) values (415, 'Last Temptation of Christ, The', 'Drama', 5);
insert into movie (title, genre, review) values (416, 'Cameraman: The Life and Work of Jack Cardiff', 'Documentary', 4);
insert into movie (title, genre, review) values (417, 'Prairie Home Companion, A', 'Comedy|Drama|Musical', 1);
insert into movie (title, genre, review) values (418, 'Paul', 'Adventure|Comedy|Sci-Fi', 4);
insert into movie (title, genre, review) values (419, 'Magnificent Seven, The', 'Adventure|Western', 4);
insert into movie (title, genre, review) values (420, 'Tank Girl', 'Action|Comedy|Sci-Fi', 2);
insert into movie (title, genre, review) values (421, 'After School Special (a.k.a. Barely Legal)', 'Comedy', 3);
insert into movie (title, genre, review) values (422, 'Swimsuit Issue, The (Allt flyter)', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values (423, 'Love Affair', 'Drama|Romance', 2);
insert into movie (title, genre, review) values (424, 'Point and Shoot', 'Documentary', 1);
insert into movie (title, genre, review) values (425, 'Ruby', 'Crime|Drama', 1);
insert into movie (title, genre, review) values (426, 'All Things to All Men', 'Crime|Thriller', 1);
insert into movie (title, genre, review) values (427, 'Gross Anatomy (a.k.a. A Cut Above)', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values (428, 'Bed & Breakfast: Love is a Happy Accident (Bed & Breakfast)', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values (429, 'Back to School', 'Comedy', 3);
insert into movie (title, genre, review) values (430, 'Sand Sharks', 'Comedy|Horror|Sci-Fi|Thriller', 4);
insert into movie (title, genre, review) values (431, 'Earth vs. The Spider', 'Horror', 4);
insert into movie (title, genre, review) values (432, 'I Don''t Want to Be a Man (Ich möchte kein Mann sein)', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values (433, 'Bring It On: All or Nothing', 'Comedy', 3);
insert into movie (title, genre, review) values (434, 'Ultrasuede: In Search of Halston', 'Documentary', 4);
insert into movie (title, genre, review) values (435, 'Les disparus de Saint-Agil', 'Drama|Mystery', 3);
insert into movie (title, genre, review) values (436, 'Romy and Michele: In the Beginning', 'Comedy', 2);
insert into movie (title, genre, review) values (437, 'Teddy Bear (Mis)', 'Comedy|Crime', 4);
insert into movie (title, genre, review) values (438, 'Trouble with Harry, The', 'Comedy|Mystery', 4);
insert into movie (title, genre, review) values (439, 'Tukkijoella', 'Drama', 3);
insert into movie (title, genre, review) values (440, '99 Homes', 'Drama', 3);
insert into movie (title, genre, review) values (441, 'Bye Bye Braverman', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (442, 'Battered Bastards of Baseball, The', 'Documentary', 3);
insert into movie (title, genre, review) values (443, 'Happy Ending, The', 'Drama', 4);
insert into movie (title, genre, review) values (444, 'How to Kill Your Neighbor''s Dog', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values (445, 'Singing Nun, The', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values (446, 'Woman, The', 'Horror', 5);
insert into movie (title, genre, review) values (447, 'Way of the Dragon, The (a.k.a. Return of the Dragon) (Meng long guo jiang)', 'Action|Crime', 2);
insert into movie (title, genre, review) values (448, 'Eat Pray Love', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (449, 'Eureka (Yurîka)', 'Drama', 3);
insert into movie (title, genre, review) values (450, 'Pear Tree, The (Derakhte Golabi)', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (451, 'Bettie Page Reveals All', 'Documentary', 1);
insert into movie (title, genre, review) values (452, 'Otakus in Love', 'Comedy|Drama|Romance', 3);
insert into movie (title, genre, review) values (453, 'Emil i Lönneberga', 'Children|Drama', 5);
insert into movie (title, genre, review) values (454, 'Green Mile, The', 'Crime|Drama', 3);
insert into movie (title, genre, review) values (455, 'Hi-Lo Country, The', 'Drama|Romance|Western', 1);
insert into movie (title, genre, review) values (456, 'Ghosts of Girlfriends Past', 'Comedy|Fantasy|Romance', 5);
insert into movie (title, genre, review) values (457, 'Creation of the Humanoids, The', 'Sci-Fi', 4);
insert into movie (title, genre, review) values (458, '2 Days in the Valley', 'Crime|Film-Noir', 4);
insert into movie (title, genre, review) values (459, 'Great Gatsby, The', 'Drama', 5);
insert into movie (title, genre, review) values (460, 'Dickson Experimental Sound Film', 'Musical', 5);
insert into movie (title, genre, review) values (461, 'Islands in the Stream', 'Drama', 2);
insert into movie (title, genre, review) values (462, 'Moscow Clad in Snow (Moscou sous la neige) ', 'Documentary', 4);
insert into movie (title, genre, review) values (463, 'Quantum of Solace', 'Action|Adventure|Thriller', 4);
insert into movie (title, genre, review) values (464, 'Cord (Hide and Seek)', 'Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values (465, 'Night Walker, The', 'Horror|Mystery|Thriller', 2);
insert into movie (title, genre, review) values (466, 'Shot at Glory, A', 'Drama', 3);
insert into movie (title, genre, review) values (467, 'Busher, The', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values (468, 'Calamity Jane', 'Musical|Western', 5);
insert into movie (title, genre, review) values (469, 'The Beaver Trilogy', 'Comedy|Documentary|Drama', 5);
insert into movie (title, genre, review) values (470, 'Dust of Time, The', 'Drama', 4);
insert into movie (title, genre, review) values (471, 'Marmaduke', 'Comedy', 2);
insert into movie (title, genre, review) values (472, 'Frank and Ollie', 'Documentary', 4);
insert into movie (title, genre, review) values (473, 'Vengo', 'Drama|Musical', 5);
insert into movie (title, genre, review) values (474, 'Mail Order Bride', 'Comedy|Western', 4);
insert into movie (title, genre, review) values (475, 'Suddenly, Last Winter (Improvvisamente l''inverno scorso)', 'Documentary', 3);
insert into movie (title, genre, review) values (476, 'Super 8', 'Mystery|Sci-Fi|Thriller|IMAX', 2);
insert into movie (title, genre, review) values (477, 'Destroyer', 'Adventure|Drama|War', 4);
insert into movie (title, genre, review) values (478, 'One True Thing', 'Drama', 1);
insert into movie (title, genre, review) values (479, 'Plastic Age, The', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values (480, 'Emperor of the North (Emperor of the North Pole)', 'Action|Drama|Thriller', 3);
insert into movie (title, genre, review) values (481, 'Everything or Nothing: The Untold Story of 007', 'Documentary', 1);
insert into movie (title, genre, review) values (482, 'Artist, The', 'Drama|Romance', 2);
insert into movie (title, genre, review) values (483, 'Thurgood', 'Drama', 2);
insert into movie (title, genre, review) values (484, 'Secondhand Lions', 'Children|Comedy|Drama', 2);
insert into movie (title, genre, review) values (485, 'Austin Powers: International Man of Mystery', 'Action|Adventure|Comedy', 1);
insert into movie (title, genre, review) values (486, 'Pont du Nord, Le', 'Comedy|Fantasy|Mystery', 1);
insert into movie (title, genre, review) values (487, 'Jason Goes to Hell: The Final Friday', 'Action|Horror', 3);
insert into movie (title, genre, review) values (488, 'Música Campesina (Country Music)', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (489, 'Necessary Roughness', 'Comedy', 5);
insert into movie (title, genre, review) values (490, 'Coherence', 'Drama|Mystery|Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values (491, 'Cinderfella', 'Comedy', 3);
insert into movie (title, genre, review) values (492, 'Louis C.K.: Chewed Up', 'Comedy', 1);
insert into movie (title, genre, review) values (493, 'Tarzan the Fearless', 'Action|Adventure', 1);
insert into movie (title, genre, review) values (494, 'Grave Halloween', 'Horror', 1);
insert into movie (title, genre, review) values (495, 'Hui Buh: The Castle Ghost', 'Adventure|Comedy|Fantasy', 4);
insert into movie (title, genre, review) values (496, 'Passion of Anna, The (Passion, En)', 'Drama', 5);
insert into movie (title, genre, review) values (497, 'Four Sons', 'Drama|War', 4);
insert into movie (title, genre, review) values (498, 'Glenn Killing på Berns', 'Comedy', 5);
insert into movie (title, genre, review) values (499, 'Public Enemy, The', 'Action|Crime|Drama', 5);
insert into movie (title, genre, review) values (500, '3-Iron (Bin-jip)', 'Drama|Romance', 5);
insert into movie (title, genre, review) values (501, 'Girls, Les', 'Musical', 5);
insert into movie (title, genre, review) values (502, 'Diabolique (Les diaboliques)', 'Horror|Mystery|Thriller', 3);
insert into movie (title, genre, review) values (503, 'Straight to Hell', 'Comedy|Crime|Western', 4);
insert into movie (title, genre, review) values (504, 'Rains Came, The', 'Adventure|Drama|Romance', 4);
insert into movie (title, genre, review) values (505, 'Asfour Stah', 'Drama', 1);
insert into movie (title, genre, review) values (506, 'Secret of Santa Vittoria, The', 'Comedy|Drama|War', 3);
insert into movie (title, genre, review) values (507, 'Red Eye', 'Horror|Thriller', 1);
insert into movie (title, genre, review) values (508, 'Drop Dead Gorgeous', 'Comedy', 5);
insert into movie (title, genre, review) values (509, 'Follow Me, Boys!', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values (510, 'Phantom of the Opera, The', 'Drama|Horror', 1);
insert into movie (title, genre, review) values (511, 'One Nation Under God ', 'Documentary', 5);
insert into movie (title, genre, review) values (512, 'Twixt', 'Horror|Thriller', 4);
insert into movie (title, genre, review) values (513, 'Noi the Albino (Nói albinói)', 'Drama', 2);
insert into movie (title, genre, review) values (514, 'Discreet Charm of the Bourgeoisie, The (Charme discret de la bourgeoisie, Le)', 'Comedy|Drama|Fantasy', 2);
insert into movie (title, genre, review) values (515, 'Hostel: Part II', 'Crime|Horror|Thriller', 2);
insert into movie (title, genre, review) values (516, 'Pigs with a P.38', '(no genres listed)', 1);
insert into movie (title, genre, review) values (517, 'Sand Pebbles, The', 'Drama|Romance|War', 5);
insert into movie (title, genre, review) values (518, 'Sherlock Jr.', 'Comedy|Fantasy|Romance', 2);
insert into movie (title, genre, review) values (519, 'Dynamite', 'Drama', 2);
insert into movie (title, genre, review) values (520, 'When the Levees Broke: A Requiem in Four Acts', 'Documentary', 4);
insert into movie (title, genre, review) values (521, 'La montaña rusa', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values (522, 'Omen IV: The Awakening', 'Horror|Mystery|Thriller', 5);
insert into movie (title, genre, review) values (523, 'O.C. and Stiggs', 'Comedy', 1);
insert into movie (title, genre, review) values (524, 'Master and Margaret, The (Il maestro e Margherita)', 'Drama|Fantasy|Romance', 5);
insert into movie (title, genre, review) values (525, 'An American Tail: The Mystery of the Night Monster', 'Adventure|Animation|Children|Fantasy|Mystery|Sci-Fi', 2);
insert into movie (title, genre, review) values (526, 'Universal Soldier', 'Action|Sci-Fi', 3);
insert into movie (title, genre, review) values (527, 'Day & Night', 'Animation|Children', 2);
insert into movie (title, genre, review) values (528, 'Hammer, The', 'Comedy', 3);
insert into movie (title, genre, review) values (529, 'Suppose They Gave a War and Nobody Came?', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values (530, 'Ogre, The (Unhold, Der)', 'Drama', 1);
insert into movie (title, genre, review) values (531, 'Leap Year (Año bisiesto)', 'Drama', 5);
insert into movie (title, genre, review) values (532, 'Last Train Home', 'Documentary|Drama', 1);
insert into movie (title, genre, review) values (533, '10 MPH', 'Documentary', 2);
insert into movie (title, genre, review) values (534, 'Can-Can', 'Comedy|Musical|Romance', 4);
insert into movie (title, genre, review) values (535, 'Kingdom of the Spiders', 'Horror|Sci-Fi', 3);
insert into movie (title, genre, review) values (536, 'Young Victoria, The', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (537, 'Gravedancers, The', 'Horror|Thriller', 2);
insert into movie (title, genre, review) values (538, 'Liliom', 'Drama|Fantasy', 1);
insert into movie (title, genre, review) values (539, 'Stanley & Iris', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (540, 'Scream, Blacula, Scream!', 'Horror', 3);
insert into movie (title, genre, review) values (541, 'Northwest', 'Action|Crime|Drama', 5);
insert into movie (title, genre, review) values (542, 'Billion Dollar Brain', 'Drama|Thriller', 3);
insert into movie (title, genre, review) values (543, 'Panic', 'Action|Thriller', 3);
insert into movie (title, genre, review) values (544, 'Murder by Proxy: How America Went Postal', 'Documentary', 4);
insert into movie (title, genre, review) values (545, 'Millie', 'Drama|Romance', 3);
insert into movie (title, genre, review) values (546, 'I Was Monty''s Double', 'Drama|War', 4);
insert into movie (title, genre, review) values (547, 'Pornorama', 'Comedy', 1);
insert into movie (title, genre, review) values (548, 'Dhobi Ghat', 'Drama', 5);
insert into movie (title, genre, review) values (549, 'Vermin', 'Comedy', 1);
insert into movie (title, genre, review) values (550, 'Tell Me and I Will Forget', 'Documentary', 3);
insert into movie (title, genre, review) values (551, 'LennoNYC', 'Documentary', 5);
insert into movie (title, genre, review) values (552, 'Beautiful City (Shah-re ziba)', 'Drama', 5);
insert into movie (title, genre, review) values (553, 'Man of Her Dreams (a.k.a. The Fiancé)', 'Drama', 4);
insert into movie (title, genre, review) values (554, 'Stakeout', 'Comedy|Crime|Romance|Thriller', 3);
insert into movie (title, genre, review) values (555, 'Bright Days Ahead', 'Drama|Romance', 1);
insert into movie (title, genre, review) values (556, 'Last Chance', 'Comedy', 4);
insert into movie (title, genre, review) values (557, 'Household Saints', 'Drama', 1);
insert into movie (title, genre, review) values (558, 'Walker, The', 'Drama|Mystery', 4);
insert into movie (title, genre, review) values (559, 'Crazy for Christmas', 'Children', 3);
insert into movie (title, genre, review) values (560, 'Chunhyang', 'Drama|Musical|Romance', 4);
insert into movie (title, genre, review) values (561, 'Warriors of Virtue', 'Action|Adventure|Children|Fantasy', 5);
insert into movie (title, genre, review) values (562, 'City Streets', 'Crime|Film-Noir', 5);
insert into movie (title, genre, review) values (563, 'Little Monsters', 'Comedy', 3);
insert into movie (title, genre, review) values (564, 'Otakus in Love', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values (565, 'Ghost Dad', 'Comedy|Fantasy', 3);
insert into movie (title, genre, review) values (566, 'African Queen, The', 'Adventure|Comedy|Romance|War', 2);
insert into movie (title, genre, review) values (567, 'Born Reckless', 'Action|Adventure|Crime|Drama|Romance', 5);
insert into movie (title, genre, review) values (568, 'Wife! Be Like a Rose! (Tsuma yo bara no yo ni)', 'Drama', 5);
insert into movie (title, genre, review) values (569, 'Santa Fe', 'Action|Romance|Western', 2);
insert into movie (title, genre, review) values (570, 'Terror Train', 'Horror', 1);
insert into movie (title, genre, review) values (571, 'Craig Ferguson: I''m Here To Help', 'Comedy|Documentary', 3);
insert into movie (title, genre, review) values (572, 'Tiny Furniture', 'Comedy', 3);
insert into movie (title, genre, review) values (573, 'Michael the Brave (Mihai Viteazul)', 'Action|Drama', 5);
insert into movie (title, genre, review) values (574, 'Island of Lost Souls', 'Adventure|Horror|Romance|Sci-Fi', 3);
insert into movie (title, genre, review) values (575, 'Egyptian, The', 'Drama', 5);
insert into movie (title, genre, review) values (576, 'Ennui, L''', 'Drama|Romance', 2);
insert into movie (title, genre, review) values (577, 'Chain Letter', 'Horror|Mystery|Thriller', 3);
insert into movie (title, genre, review) values (578, 'White Wedding (Noce blanche)', 'Drama|Romance', 4);
insert into movie (title, genre, review) values (579, 'Starship Invasions', 'Sci-Fi', 3);
insert into movie (title, genre, review) values (580, 'Return of the Living Dead Part II', 'Comedy|Horror', 4);
insert into movie (title, genre, review) values (581, 'Road, The', 'Adventure|Drama|Thriller', 1);
insert into movie (title, genre, review) values (582, 'Don Quixote', 'Adventure|Comedy|Drama', 4);
insert into movie (title, genre, review) values (583, 'Heaven''s Prisoners', 'Crime|Thriller', 1);
insert into movie (title, genre, review) values (584, 'Spencer''s Mountain', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values (585, 'For Greater Glory: The True Story of Cristiada', 'Drama|War', 1);
insert into movie (title, genre, review) values (586, 'Woody Allen: A Documentary', 'Documentary', 4);
insert into movie (title, genre, review) values (587, 'My Best Enemy (Mi mejor enemigo)', 'Drama|War', 1);
insert into movie (title, genre, review) values (588, 'New in Town', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values (589, 'Peking Opera Blues (Do ma daan)', 'Action|Comedy', 3);
insert into movie (title, genre, review) values (590, 'Chamber, The', 'Drama', 3);
insert into movie (title, genre, review) values (591, 'Accused, The', 'Drama', 5);
insert into movie (title, genre, review) values (592, 'Please Remove Your Shoes ', 'Documentary', 1);
insert into movie (title, genre, review) values (593, 'Inventing the Abbotts', 'Drama|Romance', 4);
insert into movie (title, genre, review) values (594, 'Gold Rush, The', 'Adventure|Comedy|Romance', 4);
insert into movie (title, genre, review) values (595, 'Day Without a Mexican, A', 'Comedy|Drama|Fantasy|Mystery', 5);
insert into movie (title, genre, review) values (596, 'Starship Invasions', 'Sci-Fi', 5);
insert into movie (title, genre, review) values (597, 'Orderly or Disorderly (Be Tartib ya Bedoun-e Tartib)', 'Documentary', 4);
insert into movie (title, genre, review) values (598, 'Eu Não Quero Voltar Sozinho (I Don''t Want to Go Back Alone)', 'Drama|Romance', 3);
insert into movie (title, genre, review) values (599, 'X', 'Thriller', 2);
insert into movie (title, genre, review) values (600, 'Lips of Blood (Lèvres de sang)', 'Horror', 1);
insert into movie (title, genre, review) values (601, 'At Close Range', 'Crime|Drama', 2);
insert into movie (title, genre, review) values (602, 'Anna Christie', 'Drama', 4);
insert into movie (title, genre, review) values (603, 'Until the Light Takes Us', 'Documentary', 5);
insert into movie (title, genre, review) values (604, 'Soul Surfer', 'Action|Drama', 1);
insert into movie (title, genre, review) values (605, 'Forces of Nature', 'Comedy|Romance', 3);
insert into movie (title, genre, review) values (606, 'Gloria', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values (607, 'Order, The', 'Action|Adventure|Drama|Thriller', 4);
insert into movie (title, genre, review) values (608, 'Transformers', 'Action|Sci-Fi|Thriller|IMAX', 5);
insert into movie (title, genre, review) values (609, 'Date Night', 'Action|Comedy|Romance', 5);
insert into movie (title, genre, review) values (610, 'Seraphim Falls', 'Action|Adventure|Drama|War|Western', 4);
insert into movie (title, genre, review) values (611, 'Barrens, The', 'Horror', 4);
insert into movie (title, genre, review) values (612, 'Honeymoon', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values (613, 'Prisoner, The (Island of Fire) (Huo shao dao)', 'Action|Crime|Drama', 5);
insert into movie (title, genre, review) values (614, 'Living Out Loud', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values (615, 'Wilderness', 'Horror|Thriller', 1);
insert into movie (title, genre, review) values (616, 'Jay-Z: Made in America', 'Documentary', 5);
insert into movie (title, genre, review) values (617, 'Vai~E~Vem', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (618, 'Presenting Lily Mars', 'Comedy|Musical|Romance', 2);
insert into movie (title, genre, review) values (619, 'Antboy', 'Adventure|Children|Comedy', 2);
insert into movie (title, genre, review) values (620, 'Manos: The Hands of Fate', 'Horror', 1);
insert into movie (title, genre, review) values (621, 'Bullfighter and the Lady', 'Action|Drama|Romance', 3);
insert into movie (title, genre, review) values (622, 'Edison Kinetoscopic Record of a Sneeze', 'Documentary', 5);
insert into movie (title, genre, review) values (623, 'In Our Garden', '(no genres listed)', 3);
insert into movie (title, genre, review) values (624, 'Space Amoeba (Yog: Monster from Space)', 'Action|Sci-Fi', 1);
insert into movie (title, genre, review) values (625, 'Best Man Down', 'Drama', 4);
insert into movie (title, genre, review) values (626, 'Flying Down to Rio', 'Comedy|Musical|Romance', 3);
insert into movie (title, genre, review) values (627, 'Quiet, The', 'Crime|Drama|Mystery|Thriller', 1);
insert into movie (title, genre, review) values (628, 'Oxy-Morons', 'Crime|Drama', 5);
insert into movie (title, genre, review) values (629, 'Speedway Junky', 'Drama', 1);
insert into movie (title, genre, review) values (630, 'Magnum Force', 'Action|Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values (631, 'King of Kings, The', 'Drama', 2);
insert into movie (title, genre, review) values (632, 'Greaser''s Palace', 'Comedy|Drama|Western', 2);
insert into movie (title, genre, review) values (633, 'Da Vinci Code, The', 'Drama|Mystery|Thriller', 3);
insert into movie (title, genre, review) values (634, 'On Borrowed Time', 'Comedy|Drama|Fantasy', 4);
insert into movie (title, genre, review) values (635, 'After School Special (a.k.a. Barely Legal)', 'Comedy', 1);
insert into movie (title, genre, review) values (636, 'Fjorton suger', 'Drama|Romance', 4);
insert into movie (title, genre, review) values (637, 'Murders in the Zoo', 'Crime|Horror|Mystery', 1);
insert into movie (title, genre, review) values (638, 'Setup (Set Up)', 'Action|Crime|Drama', 4);
insert into movie (title, genre, review) values (639, 'All at Sea', 'Comedy', 3);
insert into movie (title, genre, review) values (640, 'Too Hot to Handle', 'Adventure|Comedy|Romance', 3);
insert into movie (title, genre, review) values (641, 'Half Past Dead', 'Action|Crime|Thriller', 4);
insert into movie (title, genre, review) values (642, 'I Love Trouble', 'Crime|Drama', 3);
insert into movie (title, genre, review) values (643, 'Nowhere', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values (644, 'Tough Ones, The (Häjyt)', 'Action|Drama', 5);
insert into movie (title, genre, review) values (645, 'Crowd, The', 'Drama', 4);
insert into movie (title, genre, review) values (646, 'Jerry Maguire', 'Drama|Romance', 2);
insert into movie (title, genre, review) values (647, 'Bushwhacked', 'Adventure|Comedy|Crime|Mystery', 5);
insert into movie (title, genre, review) values (648, 'Big Hit, The', 'Action|Comedy|Crime', 4);
insert into movie (title, genre, review) values (649, 'Canyon, The', 'Thriller', 3);
insert into movie (title, genre, review) values (650, 'Crimes and Misdemeanors', 'Comedy|Crime|Drama', 2);
insert into movie (title, genre, review) values (651, 'Apache Country', 'Action|Western', 3);
insert into movie (title, genre, review) values (652, 'Man Exposed', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values (653, 'Document of the Dead', 'Documentary|Horror', 4);
insert into movie (title, genre, review) values (654, 'Who Is Cletis Tout?', 'Comedy', 1);
insert into movie (title, genre, review) values (655, 'Parkland', 'Drama', 2);
insert into movie (title, genre, review) values (656, 'Junkopia', 'Documentary', 2);
insert into movie (title, genre, review) values (657, 'Quicksilver Highway', 'Horror|Thriller', 1);
insert into movie (title, genre, review) values (658, 'Little Drummer Boy, The', 'Animation|Children|Musical', 3);
insert into movie (title, genre, review) values (659, 'Meet the Feebles', 'Animation|Comedy|Musical', 5);
insert into movie (title, genre, review) values (660, 'Lost and Found', '(no genres listed)', 4);
insert into movie (title, genre, review) values (661, 'Reconstruction', 'Drama|Romance', 5);
insert into movie (title, genre, review) values (662, 'Playboys, The', 'Drama|Romance', 2);
insert into movie (title, genre, review) values (663, 'Burning Plain, The', 'Drama|Romance', 5);
insert into movie (title, genre, review) values (664, 'Circle of Friends', 'Drama|Romance', 3);
insert into movie (title, genre, review) values (665, 'Nina''s Heavenly Delights', 'Comedy', 2);
insert into movie (title, genre, review) values (666, 'Sands of Iwo Jima', 'Action|Drama|Romance|War', 4);
insert into movie (title, genre, review) values (667, 'Tribes', 'Drama', 5);
insert into movie (title, genre, review) values (668, 'Man of No Importance, A', 'Drama', 1);
insert into movie (title, genre, review) values (669, 'Report, The (Gozaresh)', 'Drama', 5);
insert into movie (title, genre, review) values (670, 'Posto, Il', 'Drama', 4);
insert into movie (title, genre, review) values (671, 'Ticket To Romance (En enkelt til Korsør)', 'Comedy|Drama|Romance', 2);
insert into movie (title, genre, review) values (672, 'My Girl 2', 'Comedy|Drama|Romance', 3);
insert into movie (title, genre, review) values (673, 'Dream Home (Wai dor lei ah yut ho)', 'Horror', 4);
insert into movie (title, genre, review) values (674, 'Donovan''s Brain', 'Sci-Fi', 2);
insert into movie (title, genre, review) values (675, 'Zebrahead', 'Drama', 4);
insert into movie (title, genre, review) values (676, 'Without Lying Down: Frances Marion and the Power of Women in Hollywood', 'Documentary', 3);
insert into movie (title, genre, review) values (677, 'Star Wars: Episode I - The Phantom Menace', 'Action|Adventure|Sci-Fi', 1);
insert into movie (title, genre, review) values (678, 'B-Side', 'Comedy|Romance', 1);
insert into movie (title, genre, review) values ('Race for Your Life, Charlie Brown', 'Adventure|Animation|Children', 5);
insert into movie (title, genre, review) values ('Claire''s Knee (Genou de Claire, Le)', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Man for a Day', 'Documentary', 4);
insert into movie (title, genre, review) values ('Stuck', 'Horror|Thriller', 3);
insert into movie (title, genre, review) values ('Codebreaker', 'Documentary|Drama', 5);
insert into movie (title, genre, review) values ('Casino Royale', 'Action|Adventure|Thriller', 1);
insert into movie (title, genre, review) values ('Ten Violent Women', 'Action|Drama', 4);
insert into movie (title, genre, review) values ('Adventures of Prince Achmed, The (Abenteuer des Prinzen Achmed, Die)', 'Adventure|Animation|Fantasy|Romance', 4);
insert into movie (title, genre, review) values ('Stella', 'Drama', 5);
insert into movie (title, genre, review) values ('Courier', 'Comedy|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Vice', 'Action|Adventure|Sci-Fi|Thriller', 1);
insert into movie (title, genre, review) values ('1984 (Nineteen Eighty-Four)', 'Drama|Sci-Fi', 3);
insert into movie (title, genre, review) values ('I, the Worst of All (Yo, la peor de todas)', 'Drama', 3);
insert into movie (title, genre, review) values ('About Adam', 'Comedy', 4);
insert into movie (title, genre, review) values ('13th Warrior, The', 'Action|Adventure|Fantasy', 2);
insert into movie (title, genre, review) values ('Charlie Chan''s Greatest Case', 'Mystery', 2);
insert into movie (title, genre, review) values ('Ten Shrews, The (Kymmenen riivinrautaa)', 'Comedy', 3);
insert into movie (title, genre, review) values ('Super High Me', 'Comedy|Documentary', 5);
insert into movie (title, genre, review) values ('Redhead from Wyoming, The', 'Western', 2);
insert into movie (title, genre, review) values ('Adam''s Apples (Adams æbler)', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('Jail Bait', 'Crime|Drama', 1);
insert into movie (title, genre, review) values ('Little Men', 'Drama', 4);
insert into movie (title, genre, review) values ('Devil to Pay!, The', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Immortel (ad vitam) (Immortal)', 'Action|Adventure|Animation|Fantasy|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Holes in My Shoes', 'Documentary', 5);
insert into movie (title, genre, review) values ('Glass Web, The', 'Crime|Drama|Film-Noir', 2);
insert into movie (title, genre, review) values ('Jumpin'' Jack Flash', 'Action|Comedy|Romance|Thriller', 2);
insert into movie (title, genre, review) values ('Shadow Man', 'Action', 1);
insert into movie (title, genre, review) values ('The Gambler', 'Crime|Drama|Thriller', 3);
insert into movie (title, genre, review) values ('West Point', 'Drama|Romance', 1);
insert into movie (title, genre, review) values ('Broken Hearts Club, The', 'Drama', 3);
insert into movie (title, genre, review) values ('Witches of Eastwick, The', 'Comedy|Fantasy|Horror|Thriller', 5);
insert into movie (title, genre, review) values ('Shadows of Liberty ', 'Documentary', 1);
insert into movie (title, genre, review) values ('Honest Man: The Life of R. Budd Dwyer', 'Documentary', 2);
insert into movie (title, genre, review) values ('Startup.com', 'Documentary', 2);
insert into movie (title, genre, review) values ('Santa Claus', 'Children|Fantasy', 2);
insert into movie (title, genre, review) values ('Rapid Fire', 'Action', 1);
insert into movie (title, genre, review) values ('Witless Protection', 'Comedy', 4);
insert into movie (title, genre, review) values ('Jackass 3D', 'Action|Comedy|Documentary', 2);
insert into movie (title, genre, review) values ('Not Without My Daughter', 'Drama', 5);
insert into movie (title, genre, review) values ('Ay, Carmela! (¡Ay, Carmela!)', 'Drama|War', 3);
insert into movie (title, genre, review) values ('Parallel Sons', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Chantilly Lace', 'Drama', 4);
insert into movie (title, genre, review) values ('Luck, Trust & Ketchup: Robert Altman in Carver Country', 'Documentary', 2);
insert into movie (title, genre, review) values ('Musicwood', 'Adventure|Documentary|Drama', 2);
insert into movie (title, genre, review) values ('Finian''s Rainbow', 'Fantasy|Musical', 1);
insert into movie (title, genre, review) values ('The Sea Vultures', 'Drama', 4);
insert into movie (title, genre, review) values ('Happy End', 'Comedy', 1);
insert into movie (title, genre, review) values ('Dominion Tank Police (Dominion)', 'Action|Animation|Comedy|Sci-Fi', 4);
insert into movie (title, genre, review) values ('Freebie and the Bean', 'Action|Comedy', 2);
insert into movie (title, genre, review) values ('Apartment for Peggy', 'Drama', 4);
insert into movie (title, genre, review) values ('Tall Blond Man with One Black Shoe, The (Le grand blond avec une chaussure noire)', 'Comedy|Mystery', 3);
insert into movie (title, genre, review) values ('Frisco KThe', 'Comedy|Western', 4);
insert into movie (title, genre, review) values ('Moonlight Serenade', 'Drama', 4);
insert into movie (title, genre, review) values ('Alien Trespass', 'Comedy|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Killer Is Loose, The', 'Crime|Drama|Film-Noir', 4);
insert into movie (title, genre, review) values ('Tabu', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Mom and Dad Save the World', 'Comedy|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Aeon Flux', 'Action|Sci-Fi', 2);
insert into movie (title, genre, review) values ('Silent Trigger', 'Action|Drama', 5);
insert into movie (title, genre, review) values ('Plunkett & MaCleane', 'Action|Adventure|Drama', 1);
insert into movie (title, genre, review) values ('Geri''s Game', 'Animation|Children', 5);
insert into movie (title, genre, review) values ('Iron Eagle IV', 'Action|War', 3);
insert into movie (title, genre, review) values ('Half a Loaf of Kung Fu (Dian zhi gong fu gan chian chan)', 'Action|Comedy', 1);
insert into movie (title, genre, review) values ('Just an American Boy', 'Documentary', 2);
insert into movie (title, genre, review) values ('Km. 0 - Kilometer Zero (Kilómetro cero)', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Spook Who Sat by the Door, The', 'Action|Crime|Drama', 4);
insert into movie (title, genre, review) values ('THX 1138', 'Action|Adventure|Drama|Sci-Fi', 2);
insert into movie (title, genre, review) values ('Brown Sugar', 'Romance', 1);
insert into movie (title, genre, review) values ('Grand Theft Auto', 'Action|Comedy', 4);
insert into movie (title, genre, review) values ('Butley', 'Drama', 3);
insert into movie (title, genre, review) values ('Bittersweet Life, A (Dalkomhan insaeng)', 'Action|Crime|Drama', 5);
insert into movie (title, genre, review) values ('Dragon Ball Z: Wrath of the Dragon (Doragon bôru Z 13: Ryûken bakuhatsu!! Gokû ga yaraneba dare ga yaru)', 'Action|Adventure|Animation', 1);
insert into movie (title, genre, review) values ('Bigger, Stronger, Faster*', 'Documentary', 1);
insert into movie (title, genre, review) values ('Lucy', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Whispers in the Dark', 'Thriller', 1);
insert into movie (title, genre, review) values ('Katt Williams: The Pimp Chronicles Pt. 1', 'Comedy|Documentary', 4);
insert into movie (title, genre, review) values ('War of the Gargantuas, The (Furankenshutain no kaijû: Sanda tai Gaira)', 'Horror|Sci-Fi', 2);
insert into movie (title, genre, review) values ('...And God Spoke', 'Comedy', 2);
insert into movie (title, genre, review) values ('Spring Subway', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Ambush (Rukajärven tie)', 'Drama|Romance|War', 3);
insert into movie (title, genre, review) values ('Submarine', 'Action|Drama', 1);
insert into movie (title, genre, review) values ('Brother (Brat)', 'Crime|Drama', 1);
insert into movie (title, genre, review) values ('On a marché sur Bangkok', 'Comedy', 3);
insert into movie (title, genre, review) values ('Marrying Kind, The', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Ghost Dad', 'Comedy|Fantasy', 1);
insert into movie (title, genre, review) values ('Under Suspicion', 'Crime|Drama|Thriller', 5);
insert into movie (title, genre, review) values ('One-Eyed Monster', 'Comedy|Horror|Sci-Fi', 1);
insert into movie (title, genre, review) values ('Blind Alley', 'Crime', 3);
insert into movie (title, genre, review) values ('Secret of Moonacre, The', 'Adventure|Fantasy|Romance', 1);
insert into movie (title, genre, review) values ('Photographer (Fotoamator)', 'Documentary', 2);
insert into movie (title, genre, review) values ('Chattahoochee', 'Drama', 1);
insert into movie (title, genre, review) values ('Lake of Fire', 'Documentary', 1);
insert into movie (title, genre, review) values ('Days of Wine and Roses', 'Drama', 5);
insert into movie (title, genre, review) values ('Lost for Life', 'Crime|Documentary', 1);
insert into movie (title, genre, review) values ('Una Noche', 'Drama', 4);
insert into movie (title, genre, review) values ('Kentuckian, The', 'Drama|Western', 4);
insert into movie (title, genre, review) values ('Starbuck', 'Comedy', 2);
insert into movie (title, genre, review) values ('Darling', 'Drama', 1);
insert into movie (title, genre, review) values ('Who Am I? (Wo shi shei)', 'Action|Adventure|Comedy|Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values ('Wattstax', 'Documentary|Musical', 3);
insert into movie (title, genre, review) values ('Ironclad', 'Action|Adventure', 2);
insert into movie (title, genre, review) values ('Sin of Madelon Claudet, The', 'Drama', 3);
insert into movie (title, genre, review) values ('Closing the Ring', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Disturbing Behavior', 'Horror|Thriller', 3);
insert into movie (title, genre, review) values ('Luther', 'Drama', 3);
insert into movie (title, genre, review) values ('Teacher''s Pet', 'Animation|Children', 4);
insert into movie (title, genre, review) values ('German Doctor, The (Wakolda)', 'Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Bowery at Midnight', 'Action|Comedy|Horror', 3);
insert into movie (title, genre, review) values ('Firaaq', 'Drama', 3);
insert into movie (title, genre, review) values ('Seeking Asian Female', 'Documentary', 5);
insert into movie (title, genre, review) values ('Yes Man', 'Comedy', 1);
insert into movie (title, genre, review) values ('Foxfire', 'Drama', 4);
insert into movie (title, genre, review) values ('Sword in the Stone, The', 'Animation|Children|Fantasy|Musical', 1);
insert into movie (title, genre, review) values ('Young Again', 'Fantasy', 5);
insert into movie (title, genre, review) values ('A Cinderella Story: Once Upon a Song', 'Children|Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Feast II: Sloppy Seconds', 'Action|Comedy|Horror|Thriller', 3);
insert into movie (title, genre, review) values ('Northern Soul', 'Drama', 4);
insert into movie (title, genre, review) values ('Miracles', 'Comedy', 1);
insert into movie (title, genre, review) values ('A Pistol For Ringo', 'Action|Drama|Western', 5);
insert into movie (title, genre, review) values ('King Solomon''s Mines', 'Action|Adventure|Romance', 3);
insert into movie (title, genre, review) values ('What''s New, Pussycat', 'Comedy', 3);
insert into movie (title, genre, review) values ('Horror of Dracula (Dracula)', 'Horror', 2);
insert into movie (title, genre, review) values ('Jiro Dreams of Sushi', 'Documentary', 3);
insert into movie (title, genre, review) values ('Teen Beach Movie', 'Children|Musical', 3);
insert into movie (title, genre, review) values ('Walk to Remember, A', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Bloody Pit of Horror (Il boia scarlatto) (Virgins for the Hangman)', 'Horror', 2);
insert into movie (title, genre, review) values ('God of Cookery (Sik san)', 'Comedy', 2);
insert into movie (title, genre, review) values ('Kinsey', 'Drama', 4);
insert into movie (title, genre, review) values ('Loving Leah', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Commitments, The', 'Comedy|Drama|Musical', 4);
insert into movie (title, genre, review) values ('Everything About Mustafa (Mustafa hakkinda hersey)', 'Drama|Thriller', 4);
insert into movie (title, genre, review) values ('Urban Cowboy', 'Drama', 5);
insert into movie (title, genre, review) values ('Legend of the Guardians: The Owls of Ga''Hoole', 'Adventure|Animation|Fantasy|IMAX', 3);
insert into movie (title, genre, review) values ('Who the F**K Is Arthur Fogel', 'Documentary', 4);
insert into movie (title, genre, review) values ('Sgt. Pepper''s Lonely Hearts Club Band', 'Adventure|Musical', 1);
insert into movie (title, genre, review) values ('Rentun Ruusu', '(no genres listed)', 4);
insert into movie (title, genre, review) values ('Girl on the Bridge, The (Fille sur le pont, La)', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Go', 'Drama', 5);
insert into movie (title, genre, review) values ('Serious Man, A', 'Comedy|Drama', 2);
insert into movie (title, genre, review) values ('If Footmen Tire You What Will Horses Do?', 'Drama', 4);
insert into movie (title, genre, review) values ('Young and Prodigious T.S. Spivet, The (L''extravagant voyage du jeune et prodigieux T.S. Spivet)', 'Adventure|Children|Drama', 2);
insert into movie (title, genre, review) values ('The Finzi Detective Agency', 'Comedy|Crime', 4);
insert into movie (title, genre, review) values ('Hangover, The', 'Comedy|Crime', 3);
insert into movie (title, genre, review) values ('Land and Freedom (Tierra y libertad)', 'Drama|War', 2);
insert into movie (title, genre, review) values ('Pinocchio', 'Children|Comedy|Fantasy', 3);
insert into movie (title, genre, review) values ('Open Season 3', 'Animation|Children|Comedy', 3);
insert into movie (title, genre, review) values ('Territories ', 'Crime|Horror', 2);
insert into movie (title, genre, review) values ('Don''t Drink the Water', 'Comedy', 4);
insert into movie (title, genre, review) values ('Malaya', 'Adventure|Drama', 1);
insert into movie (title, genre, review) values ('Wild Zero', 'Action|Comedy|Horror|Romance|Sci-Fi', 5);
insert into movie (title, genre, review) values ('Heaven''s Gate', 'Western', 5);
insert into movie (title, genre, review) values ('Helter Skelter', 'Crime|Drama|Thriller', 2);
insert into movie (title, genre, review) values ('Yankee Zulu', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Across to Singapore', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Lucrèce Borgia', '(no genres listed)', 1);
insert into movie (title, genre, review) values ('Undefeatable', 'Action', 4);
insert into movie (title, genre, review) values ('Splatter University', 'Horror', 3);
insert into movie (title, genre, review) values ('Dirty Bomb', 'Comedy', 1);
insert into movie (title, genre, review) values ('Fist of Jesus', '(no genres listed)', 5);
insert into movie (title, genre, review) values ('Meteor', 'Action|Drama|Sci-Fi', 3);
insert into movie (title, genre, review) values ('L.A. Zombie', 'Horror', 1);
insert into movie (title, genre, review) values ('White God (Fehér isten)', 'Drama', 1);
insert into movie (title, genre, review) values ('Drowning by Numbers', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Gate, The', 'Horror', 5);
insert into movie (title, genre, review) values ('Night of the Creeps', 'Comedy|Horror|Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values ('Far From Home: The Adventures of Yellow Dog', 'Adventure|Children', 1);
insert into movie (title, genre, review) values ('Claire Dolan', 'Drama', 1);
insert into movie (title, genre, review) values ('Images', 'Drama|Fantasy|Horror', 5);
insert into movie (title, genre, review) values ('Ip Man: The Final Fight', 'Action|Drama', 4);
insert into movie (title, genre, review) values ('Wu Tang Master (Tian shi zhuang xie)', 'Action', 2);
insert into movie (title, genre, review) values ('A Pigeon Sat on a Branch Reflecting on Existence', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('In Name Only', 'Drama|Romance', 4);
insert into movie (title, genre, review) values ('Main Street', 'Drama', 3);
insert into movie (title, genre, review) values ('Trip, The', 'Comedy|Drama|Romance', 1);
insert into movie (title, genre, review) values ('Gorilla at Large', 'Mystery|Thriller', 1);
insert into movie (title, genre, review) values ('Stormheart', 'Children|Drama', 5);
insert into movie (title, genre, review) values ('Time That Remains, The', 'Drama', 2);
insert into movie (title, genre, review) values ('Edge of the City', 'Drama|Film-Noir', 5);
insert into movie (title, genre, review) values ('Midnight Crossing', 'Mystery|Thriller', 1);
insert into movie (title, genre, review) values ('Himalaya (Himalaya - l''enfance d''un chef)', 'Adventure|Drama', 5);
insert into movie (title, genre, review) values ('Out Cold', 'Comedy', 4);
insert into movie (title, genre, review) values ('Sparkle', 'Drama|Musical', 3);
insert into movie (title, genre, review) values ('House of Mirth, The', 'Romance', 1);
insert into movie (title, genre, review) values ('Sleuth', 'Drama|Mystery|Thriller', 1);
insert into movie (title, genre, review) values ('Phone Booth', 'Drama|Thriller', 2);
insert into movie (title, genre, review) values ('Model Couple, The (Le couple témoin)', 'Comedy', 4);
insert into movie (title, genre, review) values ('Walk Softly, Stranger', 'Crime|Drama|Film-Noir|Romance', 4);
insert into movie (title, genre, review) values ('Fear Island', 'Horror|Mystery|Thriller', 5);
insert into movie (title, genre, review) values ('Out of Balance: ExxonMobil''s Impact on Climate Change', 'Documentary', 4);
insert into movie (title, genre, review) values ('Star Wreck: In the Pirkinning', 'Action|Comedy|Sci-Fi', 3);
insert into movie (title, genre, review) values ('Riddle of the Sands, The', 'Adventure|Drama|Thriller', 1);
insert into movie (title, genre, review) values ('Fellini''s Roma (Roma)', 'Drama', 3);
insert into movie (title, genre, review) values ('Twin Peaks: Fire Walk with Me', 'Crime|Drama|Mystery|Thriller', 1);
insert into movie (title, genre, review) values ('Art of Negative Thinking, The (Kunsten å tenke negativt)', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Mardock Scramble: The Second Combustion', 'Animation|Sci-Fi', 4);
insert into movie (title, genre, review) values ('Misérables, Les', 'Drama', 2);
insert into movie (title, genre, review) values ('Busher, The', 'Comedy|Drama', 4);
insert into movie (title, genre, review) values ('Making a Killing: The Untold Story of Psychotropic Drugging', 'Documentary', 1);
insert into movie (title, genre, review) values ('1408', 'Drama|Horror|Thriller', 4);
insert into movie (title, genre, review) values ('Net 2.0, The ', 'Action|Drama|Thriller', 2);
insert into movie (title, genre, review) values ('Schindler''s List', 'Drama|War', 5);
insert into movie (title, genre, review) values ('Descent, The', 'Adventure|Drama|Horror|Thriller', 4);
insert into movie (title, genre, review) values ('Fallen Art (Sztuka spadania)', 'Action|Animation|Comedy', 3);
insert into movie (title, genre, review) values ('Step Up 3D', 'Drama|Romance', 2);
insert into movie (title, genre, review) values ('Think Like a Man', 'Comedy', 1);
insert into movie (title, genre, review) values ('Some Folks Call It a Sling Blade', 'Drama|Thriller', 4);
insert into movie (title, genre, review) values ('Third Wheel, The', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('Shining Through', 'Drama|Romance|Thriller|War', 3);
insert into movie (title, genre, review) values ('Sudden Death', 'Action', 4);
insert into movie (title, genre, review) values ('Huckleberry Finn', 'Adventure|Musical', 1);
insert into movie (title, genre, review) values ('Sandglass, The (Sanatorium pod klepsydra)', 'Mystery', 4);
insert into movie (title, genre, review) values ('Tomie: Unlimited', 'Horror', 3);
insert into movie (title, genre, review) values ('Orphan', 'Drama|Horror|Mystery|Thriller', 5);
insert into movie (title, genre, review) values ('Citizen Kane', 'Drama|Mystery', 5);
insert into movie (title, genre, review) values ('Fantasia', 'Animation|Children|Fantasy|Musical', 2);
insert into movie (title, genre, review) values ('Searching for Debra Winger', 'Documentary', 1);
insert into movie (title, genre, review) values ('Tangerines', 'Drama', 4);
insert into movie (title, genre, review) values ('Entertaining Angels: The Dorothy Day Story', 'Drama', 1);
insert into movie (title, genre, review) values ('Thirty-Five Something (Tout pour plaire)', 'Comedy', 3);
insert into movie (title, genre, review) values ('Sexy Nights of the Living Dead', 'Horror', 2);
insert into movie (title, genre, review) values ('Captain Corelli''s Mandolin', 'Drama|Romance|War', 1);
insert into movie (title, genre, review) values ('Ordinary Miracles', 'Drama', 2);
insert into movie (title, genre, review) values ('Marsh, The', 'Horror|Thriller', 3);
insert into movie (title, genre, review) values ('Happy, Texas', 'Comedy', 2);
insert into movie (title, genre, review) values ('What If', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Servant, The', 'Drama', 1);
insert into movie (title, genre, review) values ('Donos de Portugal', 'Documentary', 3);
insert into movie (title, genre, review) values ('Going in Style', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('More Dead Than Alive', 'Romance|Western', 3);
insert into movie (title, genre, review) values ('Lay of the Land, The', 'Comedy|Drama', 5);
insert into movie (title, genre, review) values ('Hard-Boiled (Lat sau san taam)', 'Action|Crime|Drama|Thriller', 1);
insert into movie (title, genre, review) values ('Crazy, StupLove.', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values ('Kill a Rat', 'Crime|Drama|Mystery', 1);
insert into movie (title, genre, review) values ('Late Bloomers', 'Comedy', 4);
insert into movie (title, genre, review) values ('Cabiria', 'Adventure|Drama|War', 2);
insert into movie (title, genre, review) values ('Assisted Living', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Go Figure (Va savoir)', 'Comedy|Drama|Romance', 1);
insert into movie (title, genre, review) values ('All the Real Girls', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Charlotte Gray', 'Drama|Romance', 3);
insert into movie (title, genre, review) values ('Oxygen', 'Drama|Musical', 1);
insert into movie (title, genre, review) values ('Saw III', 'Crime|Horror|Thriller', 3);
insert into movie (title, genre, review) values ('Plague Dogs, The', 'Adventure|Animation|Drama', 4);
insert into movie (title, genre, review) values ('Fair Game', 'Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Woman Under the Influence, A', 'Drama', 4);
insert into movie (title, genre, review) values ('Lunch Break', 'Documentary', 3);
insert into movie (title, genre, review) values ('Our Daily Bread (Unser täglich Brot)', 'Documentary', 4);
insert into movie (title, genre, review) values ('South of the Border', 'Documentary', 4);
insert into movie (title, genre, review) values ('Transylvania 6-5000', 'Comedy|Horror', 3);
insert into movie (title, genre, review) values ('Some Days Are Better Than Others', 'Drama', 2);
insert into movie (title, genre, review) values ('God is Great, I''m Not (Dieu est grand, je suis toute petite)', 'Comedy|Romance', 5);
insert into movie (title, genre, review) values ('Dead Girl, The', 'Drama|Mystery|Thriller', 1);
insert into movie (title, genre, review) values ('Quantum of Solace', 'Action|Adventure|Thriller', 3);
insert into movie (title, genre, review) values ('Bridget Jones: The Edge of Reason', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Three Brave Men', 'Drama', 2);
insert into movie (title, genre, review) values ('Melissa P.', 'Drama', 5);
insert into movie (title, genre, review) values ('Human Centipede II (Full Sequence), The', 'Horror', 5);
insert into movie (title, genre, review) values ('Son of Batman', 'Action|Adventure|Animation|Crime|Fantasy', 3);
insert into movie (title, genre, review) values ('Treacle Jr.', 'Drama', 4);
insert into movie (title, genre, review) values ('301, 302 (301/302)', 'Horror|Mystery|Thriller', 2);
insert into movie (title, genre, review) values ('Mad Dog and Glory', 'Comedy|Drama|Romance', 5);
insert into movie (title, genre, review) values ('Ciao Manhattan (Ciao! Manhattan)', 'Documentary|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Oath, The', 'Documentary', 3);
insert into movie (title, genre, review) values ('Sweeney Todd: The Demon Barber of Fleet Street', 'Drama|Horror|Musical|Thriller', 1);
insert into movie (title, genre, review) values ('Cry-Baby', 'Comedy|Musical|Romance', 2);
insert into movie (title, genre, review) values ('Tasting Menu', 'Comedy', 1);
insert into movie (title, genre, review) values ('Defender, The', 'Action', 5);
insert into movie (title, genre, review) values ('Tokyo Chorus (Tôkyô no kôrasu)', 'Comedy|Drama', 1);
insert into movie (title, genre, review) values ('Same Time, Next Year', 'Comedy|Drama|Romance', 4);
insert into movie (title, genre, review) values ('Khartoum', 'Action|Adventure|Drama|War', 1);
insert into movie (title, genre, review) values ('Maps to the Stars', 'Drama', 2);
insert into movie (title, genre, review) values ('Pizzas', 'Drama', 4);
insert into movie (title, genre, review) values ('Hum Aapke Hain Koun...!', 'Comedy|Drama|Musical', 3);
insert into movie (title, genre, review) values ('Ghost Ship, The', 'Drama|Mystery|Thriller', 2);
insert into movie (title, genre, review) values ('Backflash (Backflash Blues)', 'Action|Crime|Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Sniper: Reloaded ', 'Action|Drama|Thriller|War', 3);
insert into movie (title, genre, review) values ('Blonde Venus', 'Drama', 4);
insert into movie (title, genre, review) values ('Windmill Movie, The', 'Documentary', 4);
insert into movie (title, genre, review) values ('Forever Hardcore: The Documentary', 'Documentary', 5);
insert into movie (title, genre, review) values ('Mitä meistä tuli', 'Crime|Drama|Thriller', 2);
insert into movie (title, genre, review) values ('Soloist, The', 'Drama|Musical', 3);
insert into movie (title, genre, review) values ('Texas Chainsaw Massacre: The Beginning, The', 'Horror|Thriller', 1);
insert into movie (title, genre, review) values ('Arrowhead', 'Drama|Western', 2);
insert into movie (title, genre, review) values ('Second Wind (Le deuxième souffle) (Second Breath)', 'Crime|Drama|Film-Noir', 5);
insert into movie (title, genre, review) values ('B.U.S.T.E.D (Everybody Loves Sunshine) (Busted)', 'Crime|Drama', 4);
insert into movie (title, genre, review) values ('Rembrandt''s J''accuse', 'Documentary|Mystery', 4);
insert into movie (title, genre, review) values ('Koumiko Mystery, The (Mystère Koumiko, Le)', 'Documentary', 2);
insert into movie (title, genre, review) values ('Other Shore, The', 'Adventure|Documentary', 4);
insert into movie (title, genre, review) values ('Thérèse', 'Drama', 5);
insert into movie (title, genre, review) values ('Those Who Love Me Can Take the Train (Ceux qui m''aiment prendront le train)', 'Drama', 5);
insert into movie (title, genre, review) values ('Melissa P.', 'Drama', 1);
insert into movie (title, genre, review) values ('Harvey Girls, The', 'Comedy|Musical|Western', 5);
insert into movie (title, genre, review) values ('Phantasm II', 'Action|Fantasy|Horror|Sci-Fi|Thriller', 3);
insert into movie (title, genre, review) values ('Contact', 'Drama|Sci-Fi', 2);
insert into movie (title, genre, review) values ('Sliver', 'Thriller', 1);
insert into movie (title, genre, review) values ('Towelhead (a.k.a. Nothing is Private)', 'Drama', 1);
insert into movie (title, genre, review) values ('Noises Off...', 'Comedy', 3);
insert into movie (title, genre, review) values ('Taira Clan Saga, The (Shin heike monogatari)', 'Drama', 1);
insert into movie (title, genre, review) values ('Heavenly Body, The', 'Comedy|Romance', 4);
insert into movie (title, genre, review) values ('After Alice (Eye of the Killer)', 'Crime|Drama|Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('Hotel Pacific (Zaklete rewiry)', 'Drama', 1);
insert into movie (title, genre, review) values ('Perfect Man, The', 'Comedy|Drama|Romance', 2);
insert into movie (title, genre, review) values ('Notorious Landlady, The', 'Comedy|Mystery', 1);
insert into movie (title, genre, review) values ('The Gamers', 'Adventure|Comedy|Fantasy', 1);
insert into movie (title, genre, review) values ('Story of Xinghua, The (Xinghua san yue tian)', 'Drama', 4);
insert into movie (title, genre, review) values ('23 (23 - Nichts ist so wie es scheint)', 'Drama|Thriller', 3);
insert into movie (title, genre, review) values ('Return of Martin Guerre, The (Retour de Martin Guerre, Le)', 'Drama', 3);
insert into movie (title, genre, review) values ('Artois the Goat', 'Comedy', 1);
insert into movie (title, genre, review) values ('Tormento', 'Drama', 2);
insert into movie (title, genre, review) values ('Mall', 'Drama', 2);
insert into movie (title, genre, review) values ('Tuxedo, The', 'Action|Comedy', 3);
insert into movie (title, genre, review) values ('Half Life of Timofey Berezin, The (PU-239)', 'Drama', 2);
insert into movie (title, genre, review) values ('Woman Who Wasn''t There, The', 'Documentary', 4);
insert into movie (title, genre, review) values ('Farewell, The (Abschied - Brechts letzter Sommer)', 'Drama', 4);
insert into movie (title, genre, review) values ('Family Law (Derecho de familia)', 'Comedy|Drama', 3);
insert into movie (title, genre, review) values ('Final Destination 3', 'Horror|Mystery|Thriller', 4);
insert into movie (title, genre, review) values ('Jim Jefferies: BARE', 'Comedy', 4);
insert into movie (title, genre, review) values ('Richard III', 'Drama|War', 3);
insert into movie (title, genre, review) values ('Kids in the Hall: Same Guys, New Dresses', 'Comedy|Documentary', 4);
insert into movie (title, genre, review) values ('Eye for an Eye, An', 'Action|Crime|Thriller', 4);
insert into movie (title, genre, review) values ('Yakuza, The', 'Drama', 2);
insert into movie (title, genre, review) values ('Rocket, The', 'Drama', 3);